var _arAdmShow=[],_arAdmNotShow=[],_arAdmCp=[],_chkPr=!1,_arNPr=[],_trackingSend=false, _arrBoxApp=[],_admDefault={},imgHost='http://admicro2.vcmedia.vn/adt/cpc/',admImgHost=false,_admTrackRequest={'balloon':[],'boxapp':[]};

window.ADS_CHECKER={pr:null,RAND:Math.random(),getPath2Check:function(a){var c=document.URL,d=document.referrer;return("Site:Pageurl"==a?c.replace(/\?i=([0-9]+)&bz=([0-9]+)&z=([0-9]+)#([0-9_0-9]+)/g,""):d.replace(/\?i=([0-9]+)&bz=([0-9]+)&z=([0-9]+)#([0-9_0-9]+)/g,"")).toLowerCase()},plugin:new function(){var a,c,d,b,f,g=this;g.installed=!1;g.raw="";g.major=-1;g.minor=-1;g.revision=-1;g.revisionStr="";var l=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(a){return v(a)}},{name:"ShockwaveFlash.ShockwaveFlash.6",
version:function(a){var b="6.0.r21";try{a.AllowScriptAccess="always",b=v(a)}catch(c){}return b}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(a){return v(a)}}],v=function(a){var b=-1;try{b=a.GetVariable("$version")}catch(c){}return b};g.majorAtLeast=function(a){return g.major>=a};g.minorAtLeast=function(a){return g.minor>=a};g.revisionAtLeast=function(a){return g.revision>=a};g.versionAtLeast=function(a){var b=[g.major,g.minor,g.revision],c=Math.min(b.length,arguments.length);for(i=0;i<
c;i++)if(b[i]>=arguments[i]){if(!(i+1<c&&b[i]==arguments[i]))return!0}else return!1};if(navigator.plugins&&0<navigator.plugins.length){if((l=navigator.mimeTypes)&&l["application/x-shockwave-flash"]&&l["application/x-shockwave-flash"].enabledPlugin&&l["application/x-shockwave-flash"].enabledPlugin.description){var z=l["application/x-shockwave-flash"].enabledPlugin.description,G=z,l=G.split(/ +/),z=l[2].split(/\./),l=l[3];a=G;c=parseInt(z[0],10);d=parseInt(z[1],10);b=l;f=parseInt(l.replace(/[a-zA-Z]/g,
""),10)||g.revision;g.raw=a;g.major=c;g.minor=d;g.revisionStr=b;g.revision=f;g.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript)for(z=-1,G=0;G<l.length&&-1==z;G++){a=-1;try{a=new ActiveXObject(l[G].name)}catch(t){a={activeXError:!0}}a.activeXError||(g.installed=!0,z=l[G].version(a),-1!=z&&(a=z,b=a.split(","),c=parseInt(b[0].split(" ")[1],10),d=parseInt(b[1],10),f=parseInt(b[2],10),b=b[2],g.raw=a.replace("Shockwave Flash ",""),g.major=c,g.minor=d,g.revision=f,g.revisionStr=
b))}},checker:function(a,c,d){c=this.getPath2Check(c);switch(d){case "==":return c==a;case "!=":return c!=a;case "=~":return ADS_CHECKER.stripos(c,a,0);case "!~":return!ADS_CHECKER.stripos(c,a,0);case "=x":return a=RegExp(a),a.test(c);case "!x":return a=RegExp(a),!a.test(c)}return!1},weightScreen:function(){var a=!1;1100<=parseInt(screen.width)&&(a=!0);return a},chkOption:function(a,c){var d=","+a.replace(/,/g,",|,")+",";return RegExp(d,"i").test(","+c+",")},reTarget:function(){},getWeight:function(a,
c){a=a.toString();arrWeight=a.split(",");return 1<arrWeight.length?(""==c||"0"==c)&&0<parseInt(arrWeight[0])?parseInt(arrWeight[0]):"1"==c&&0<parseInt(arrWeight[1])?parseInt(arrWeight[1]):"2"==c&&0<parseInt(arrWeight[2])?parseInt(arrWeight[2]):"3"==c&&0<parseInt(arrWeight[3])?parseInt(arrWeight[3]):0:0==parseInt(arrWeight[0])?1:parseInt(arrWeight[0])},getQuery:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=RegExp("[\\?&]"+a+"=([^&#]*)"),c=c.exec(document.referrer);return null==
c?(c=RegExp("[\\?&]"+a+"=([^&#]*)"),c=c.exec(document.URL),null==c?"":decodeURIComponent(c[1].replace(/\+/g," "))):decodeURIComponent(c[1].replace(/\+/g," "))},getElementTop:function(a){if(document.getElementById)var c=document.getElementById(a);else document.all&&(c=document.all[a]);if(null!=c){yPos=c.offsetTop;for(tempEl=c.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 0},checker_checker:function(a,c){if(a){for(var d=a.length,b="",f="",g=0;g<d;g++)if(void 0==
a[g].data){for(var l="",v=0;v<a[g].length;v++)f="or"==a[g][v].join?"||":"&&",l+=(0!=v?f:"")+ADS_CHECKER.checker(a[g][v].data,a[g][v].type,a[g][v].logic);b+=(0!=g?c:"")+"("+l+")"}else b+=(0!=g?c:"")+ADS_CHECKER.checker(a[g].data,a[g].type,a[g].logic);return b}return!1},setStorage:function(a,c,d,b,f,g){"localStorage"in window&&null!==window.localStorage?(ADS_CHECKER.lcStorage.set_item(a,c,d),"__R"==a&&"__RC"==a||ADS_CHECKER.setCookie(a,c,d,b,f,g)):ADS_CHECKER.setCookie(a,c,d,b,f,g)},getStorage:function(a){return"localStorage"in
window&&null!==window.localStorage?"__R"==a||"__RC"==a?ADS_CHECKER.getCookie(a):ADS_CHECKER.lcStorage.get_item(a):ADS_CHECKER.getCookie(a)},lcStorage:{timestamp:"timestamp_",get_exprises:function(a,c,d,b){c=a.indexOf(c,d);d=a.length-1;return-1!=c?(b=a.indexOf(b,c),-1==b&&(b=d),a.substring(c,b)):""},set_item:function(a,c,d){var b="",f=(new Date).getTime(),g=this.timestamp,f=0==d||""==d?f+864E5:f+6E4*d,b="_azs"==a?";":",";d=this.get_exprises(c,g,0,b);c=""==d?c+(g+f.toString()+b):c.replace(d,g+f.toString());
localStorage.setItem(a,c)},get_item:function(a,c){var d=localStorage.getItem(a),b=(new Date).getTime(),f=this.timestamp;if(""==d||null==d)return"";endchar="_azs"==a?";":",";var g=this.get_exprises(d,f,0,endchar),g=g.replace(f,"");if(""==g||isNaN(parseInt(g))||parseInt(g)<b)return"";"undefined"!=typeof c&&(d=d.replace(f+g+endchar,""));return d},remove_item:function(a){localStorage.removeItem(a)},flush:function(){localStorage.clear()}},rand:function(a,c){var d=arguments.length;if(0==d)a=0,c=2147483647;
else if(1==d)throw Error("Error");return Math.floor(Math.random()*(c-a+1))+a},subCookie:function(a,c,d){c=a.indexOf(c,d);d=a.length-1;if(-1!=c){var b=a.indexOf(";",c);-1==b&&(b=d);return a.substring(c,b)}return""},popup_setCookie:function(a,c,d,b,f,g){d=(new Date(+new Date+6E5)).toGMTString();a=[a+"="+escape(c)];for(var l in d={expires:d,path:b,domain:f})d[l]&&a.push(l+"="+d[l]);return g&&a.push("secure"),document.cookie=a.join(";"),!0},setCookie:function(a,c,d,b,f,g){(new Date).getTime();b=""==b?
"/":b;d=0==d||""==d?(new Date(+new Date+864E5)).toGMTString():(new Date(+new Date+6E4*d)).toGMTString();a=[a+"="+escape(c)];for(var l in d={expires:d,path:b,domain:f})d[l]&&a.push(l+"="+d[l]);return g&&a.push("secure"),document.cookie=a.join(";"),!0},getCookie:function(a){return 0<document.cookie.length&&(c_start=document.cookie.indexOf(a+"="),-1!=c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,
c_end))):""},in_array:function(a,c,d){var b=!1,f;d=!!d;for(f in c)if(d&&c[f]===a||!d&&c[f]==a){b=!0;break}return b},in_array_position:function(a,c,d){var b=0;d=!!d;for(var f=0,g=c.length;f<g;f++){if(d&&c[f]===a||!d&&c[f]==a)return f;b++}return-1},array_duplicate:function(a,c){var d=[];if(0!=a.length&&0!=c.length)for(var b=0,f=a.length;b<f;b++)ADS_CHECKER.in_array(a[b],c)&&(d[d.length]=a[b]);return d},array_diff:function(a,c){for(var d=[],b=0,f=a.length;b<f;b++)ADS_CHECKER.in_array(a[b],c)||(d[d.length]=
a[b]);return d},stripos:function(a,c,d){a=(a+"").toLowerCase();c=(c+"").toLowerCase();return-1!==a.indexOf(c,d)},processClick:function(a,c){for(var d=c.length,b=0;b<d;b++){var f=document.createElement("iframe");f.width=0;f.height=0;f.style.border=0;f.src=c;document.getElementById(a).appendChild(f)}},randBanner:function(){return 0==Math.floor(100*Math.random())%2?0:1}};
var ADS_Location=ADS_CHECKER.getStorage("__R"),ADS_City=ADS_CHECKER.getStorage("__RC"),ADS_Game=ADS_CHECKER.getStorage("g"),ADS_Gender=ADS_CHECKER.getStorage("s"),ADS_Age=ADS_CHECKER.getStorage("a"),ADS_UserInfo=ADS_CHECKER.getCookie("__ui");ADS_CHECKER.flash=ADS_CHECKER.plugin.installed;ADS_Game=""==ADS_Game?0:parseInt(ADS_Game.toString().replace(/timestamp_([0-9]+)\,/g,""));ADS_Gender=""==ADS_Gender?0:parseInt(ADS_Gender.toString().replace(/timestamp_([0-9]+)\,/g,""));
ADS_Age=""==ADS_Age?0:parseInt(ADS_Age.toString().replace(/timestamp_([0-9]+)\,/g,""));ADS_UserInfo=""==ADS_UserInfo?"":parseInt(ADS_UserInfo.toString().replace(/timestamp_([0-9]+)\,/g,""));
""!=ADS_Location&&(0<=parseInt(ADS_Location)&&3>=parseInt(ADS_Location)?""!=ADS_City&&"undefined"!=typeof ADS_City||ADS_CHECKER.setStorage("__RC",ADS_Location,"","/"):(4==parseInt(ADS_Location)||7<=parseInt(ADS_Location)&&31>parseInt(ADS_Location)?ADS_CHECKER.setStorage("__R","1","","/"):31<=parseInt(ADS_Location)||51>=parseInt(ADS_Location)?ADS_CHECKER.setStorage("__R","2","","/"):ADS_CHECKER.setStorage("__R","3","","/"),ADS_CHECKER.setStorage("__RC",ADS_Location,"","/")),"0"==ADS_Location&&"0"!=
ADS_City&&(4==parseInt(ADS_City)||7<=parseInt(ADS_City)&&31>parseInt(ADS_City)?(ADS_Location=1,ADS_CHECKER.setStorage("__R","1","","/")):31<=parseInt(ADS_City)&&51>=parseInt(ADS_City)?(ADS_Location=2,ADS_CHECKER.setStorage("__R","2","","/")):100>=parseInt(ADS_City)&&(ADS_Location=3,ADS_CHECKER.setStorage("__R","3","","/"))));
function banner(a){if(a){a={bid:parseInt(a.bid),title:a.title,type:a.type,link:a.link,src:a.src,alt:a.alt?a.alt:"",location:a.location,width:parseInt(a.width),height:parseInt(a.height),created:a.created?a.created:null,expired:a.expired?a.expired:null,slotIdx:a.slotIdx,attr:a.attr,terms:a.terms,clicks:a.clicks?a.clicks:null,views:a.views?a.views:null,cpname:a.cpname,counter:a.counter,iframe:a.iframe,sort:a.sort,cpm:a.cpm?a.cpm:0,link_clicks:a.link_clicks,link_views:a.link_views,weight:a.weight?a.weight:
0===a.weight?0:1,gr:a.gr?a.gr:0,pr:a.pr?a.pr:"",is_default:a.is_default?a.is_default:0,bannertype:a.bannertype?a.bannertype:0,re:a.re?a.re:"",ckPr:!1,bool:!1,empty:a.empty?a.empty:0,tracking:0};for(var c in a)this[c]=a[c]}}
banner.prototype.logging=function(a,c,d,b){var f=this.link?this.link:"-1";c?(c="http://logging.admicro.vn/_adv.gif",f=b?encodeURIComponent(c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_random="+d):c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_random="+d):(c="http://c.logging.admicro.vn/_adc.html",
f=b?encodeURIComponent(c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_rehttp="+escape(f)+"&adm_random="+d):c+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(this.cpname?this.cpname:"")+"&adm_aditem="+this.bid+"&adm_zoneid="+a+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(f)+"&adm_random="+d);return f};
banner.prototype.renderLinkViews=function(){var a="";if(null!=this.link_views){var c=this.link_views.length;if(document.images)for(var d=[],b=0;b<c;b++)d[b]=new Image,d[b].src=this.link_views[b];else a+='<div style="position:absolute;background:url('+this.link_views[b]+');height:0; width:0" ><span style="height:0; width:0"></span></div>'}return a};
banner.prototype.renderLinkClicks=function(a){var c="";if(null!=this.link_clicks){c="swf"==this.type?c+'onmousedown="':c+'onclick="';c+="ADS_CHECKER.processClick('"+a+"',[";a=this.link_clicks.length;for(var d=0;d<a;d++)c+="'"+this.link_clicks[d]+"'"+(d<a-1?",":"");c+=']);"'}return c};
banner.prototype.renderBanner=function(a,c,d,b,f){f='<div id="'+a+'" class="'+f+'" '+(b?'style="display:none"':"")+">";switch(this.type){case "gif":case "jpeg":case "png":f+=this.renderBannerImage(a,c,d,b);break;case "swf":f+=this.renderBannerFlash(a,c,d,b);break;case "html":a=""==ADS_Location||isNaN(parseInt(ADS_Location))||"0"==ADS_Location?1:parseInt(ADS_Location);b=this.src;var g=ADS_CHECKER.getQuery("z");parseInt(ADS_CHECKER.getQuery("bz"));var l=parseInt(ADS_CHECKER.getQuery("i"));""!=g&&""!=
l?(b=b.replace(/(ssvzone|pluszone)_([0-9]+).js/,"$1_$2_"+a+".js?random="+Math.random()),b=b.replace(/cpmzone_([0-9]+).js/,"cpmzone_$1.js?random="+Math.random())):b=b.replace(/(ssvzone|pluszone)_([0-9]+).js/,"$1_$2_"+a+".js");f+=(b+"").replace(/\0/g,"0").replace(/\\([\\'"])/g,"$1")}this.counter&&(document.images?(new Image).src=this.logging(c,!0,d):f+='<div style="background:url('+this.logging(c,!0,d)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>');
return f+this.renderLinkViews()+"</div>"};banner.prototype.renderBannerImage=function(a,c,d,b){b='<img border="0" id="'+a+'" src="'+(admImgHost?this.src.replace("admicro2.","admicro2-hcm."):this.src)+'"'+(this.width?' width="'+this.width+'"':"")+(this.height?' height="'+this.height+'"':"");if(this.attr)for(var f in this.attr)b+=" "+f+'="'+this.attr[f]+'"';b+=" "+this.renderLinkClicks(a)+" />";return this.link?'<a href="'+this.logging(c,!1,d)+'" target="_blank">'+b+"</a>":b};
banner.prototype.renderBannerFlash=function(a,c,d,b){b="";var f=this.link?"alink1="+this.logging(c,!1,d,!0)+"&amp;atar1=_blank":"",g=!1;if(this.attr)for(var l in this.attr)"flashvars"==l&&(this.attr[l]=f+"&amp;"+this.attr[l],g=!0),b+=" "+l+'="'+this.attr[l]+'"';""==f||g||(b+=' flashvars="'+f+'"');if(ADS_CHECKER.flash)return"<embed "+this.renderLinkClicks(a)+' src="'+(admImgHost?this.src.replace("admicro2.","admicro2-hcm."):this.src)+'" height="'+this.height+'" alt="'+this.alt+'" align="middle" width="'+
this.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+b+' allowscriptaccess="always" wmode="transparent" quality="high" />';if(null!=this.alt&""!=this.alt){b='<img border="0" id="'+a+'" src="'+(admImgHost?this.alt.replace("admicro2.","admicro2-hcm."):this.alt)+'"'+(this.width?' width="'+this.width+'"':"")+(this.height?' height="'+this.height+'"':"");if(this.attr)for(l in this.attr)b+=" "+l+'="'+this.attr[l]+'"';b+=" "+this.renderLinkClicks(a)+
" />";return this.link?'<a href="'+this.logging(c,!1,d)+'" target="_blank">'+b+"</a>":b}return"<embed "+this.renderLinkClicks(a)+' src="'+(admImgHost?this.src.replace("admicro2.","admicro2-hcm."):this.src)+'" height="'+this.height+'" alt="'+this.alt+'" align="middle" width="'+this.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+b+' allowscriptaccess="always" wmode="transparent" quality="high" />'};
banner.prototype.time=function(){return ads_time_server?ads_time_server:Math.round((new Date).getTime()/1E3)};banner.prototype.checkViews=function(a){a=a.substring(0,a.length-1);eval("view = view_"+a+this.bid);return!0};banner.prototype.checkClicks=function(a){a=a.substring(0,a.length-1);eval("click = click_"+a+this.bid);return!0};banner.prototype.checkExpired=function(){var a=this.time();return this.created<a&&null==this.expired||this.created<a&&a<this.expired?!1:!0};
banner.prototype.checkInvalid=function(a){return!this.checkExpired()&&this.checkViews(a)&&this.checkClicks(a)?!0:!1};banner.prototype.checkPr=function(){var a=document.URL,c=this.pr.split("|");this.ckPr=!1;for(var d=0,b=c.length;d<b;d++)if(-1!=a.indexOf(c[d]))return _chkPr=this.ckPr=!0;return!1};
banner.prototype.process=function(){if(this.terms){for(var a=this.terms,c=a.length,d="",b="",f=0;f<c;f++)0!=f&&(b="or"==a[f].join?"||":"&&"),d=a[f].channel?d+(b+("!~"==a[f].logic?"!":"")+"("+ADS_CHECKER.checker_checker(a[f].data,"=="==a[f].logic?"&&":"||")+")"):d+(b+ADS_CHECKER.checker(a[f].data,a[f].type,a[f].logic));this.bool=eval(d)}else this.bool=!0;"undefined"!=typeof __arCPM4K&&(0!=__arCPM4K.length&&ADS_CHECKER.in_array(this.bid,__arCPM4K))&&(this.bool=!1);1===this.gr&&ADS_CHECKER.in_array(parseInt(this.cpname),
_arAdmNotShow)&&(this.bool=!1);""!=this.pr?this.bool=this.checkPr():_chkPr&&(this.bool=!1);ADS_CHECKER.flash||(""!=this.alt||"swf"!=this.type)||(this.bool=!1);if(this.bool&&""!=this.re&&(a=this.re.split("|"),0<a.length)){c=!1;d=","+ADS_UserInfo+",";for(f=0;4>f;f++)"undefined"==typeof a[f]&&(a[f]=""),a[f]=a[f].replace(/[0-3]:/,""),b=","+a[f].replace(/\,/g,",|,")+",",b=RegExp(b),c=0==f?b.test(d):ADS_Location==f?c||b.test(d):c;this.bool=c}!this.bool||13!=this.bannertype&&4!=this.bannertype&&9!=this.bannertype||
(this.tracking=1);9==this.bannertype&&ADS_CHECKER.flash&&(this.bool=this.bool&&ADS_CHECKER.weightScreen());var f=this.location,f="undefined"==f||null==f?0:f,f=","+(""==f?0:f)+",",a=","+ADS_Location+",",c=","+ADS_City+",",d=this.weight,b=[],d=d.toString(),b=d.split(","),g=/,[1|2|3],[1|2|3],[1|2|3],/g;(this.bool=this.bool&&(",,"==f||g.test(f)||",0,"==f||-1!=f.toString().indexOf(c)||-1!=f.toString().indexOf(a)?!0:!1))&&1<b.length&&!(0<parseInt(b[0])&&(",,"==a||",0,"==a)||0<parseInt(b[1])&&",1,"==a||
0<parseInt(b[2])&&",2,"==a||0<parseInt(b[3])&&",3,"==a)&&(this.bool=this.bool&&!1);!this.bool||(6!=this.bannertype&&12!=this.banertype||0!=ADS_CHECKER.getWeight(d,ADS_Location)&&1!=ADS_CHECKER.getWeight(d,ADS_Location))||(1<_arrBoxApp.length&&(this.bool=!1),_arrBoxApp.push(this.bid));1==this.empty&&(this.bool=!1)};
function zone(a,c,d,b,f){var g=document.domain+"";(-1!=g.indexOf("tamdiem.net")|| -1!=g.indexOf("hay88.com"))&&"undefined"!=typeof __isPorn&&0<__isPorn.length&&0.5<=__isPorn[0]&&(_chkPr=!0);"undefined"==typeof _admDefault[a]&&(_admDefault[a]={});_admDefault[a].effect=c.effect;_admDefault[a].rotate=c.slots_rotate;a={banners:[],zoneid:a?a:-1,width:d,height:b,attr:f,style:c,share:c.share?c.share:3,slots:null,time:1E4,preload_time:3E3,rand_num:ADS_CHECKER.RAND,theme:[],run_fix:!1,cpm:null,cpd:null,ie:"Opera"==navigator.appName||
"Microsoft Internet Explorer"==navigator.appName};for(var l in a)this[l]=a[l]}zone.prototype.removeHidden=function(a){};zone.prototype.removeHtml=function(a){for(var c=1;c<=this.style.slot;c++){var d=a.indexOf("slot"+c+"_content"),b=a.lastIndexOf("<div",d),f=a.indexOf("</div>",d);0<=d&&(d=a.substring(b,f+6),a=a.replace(d,""))}return a};
zone.prototype.changeHtml=function(a){for(var c=[],d=1;d<=this.style.slot;d++){var b=a.indexOf("slot"+d+"_content"),f=a.lastIndexOf("<div",b),g=a.indexOf("</div>",b);0<=b&&(b=a.substring(f,g+6),f=b.replace("slot"+d+"_content",""),a=a.replace(b,f),c.push(d))}this.slotHide=c;return a};
zone.prototype.hideSlotNone=function(){for(var a=this.slotHide,c=!1,d="ads_zone"+this.zoneid,b=0,f=a.length;b<f;b++){var g=document.getElementById("ads_zone"+this.zoneid+"_slot"+a[b]);g?g.style.display="none":c=!0}c&&setTimeout(function(){window[d].hideSlotNone()},100)};zone.prototype.mkRandCPM=function(a){var c=0,d;for(d in a)c+=parseInt(a[d]);var b=[],f=0;for(d in a)b.push((0<f?b[f-1]:0)+Math.floor(1E3*parseInt(a[d])/c)/1E3),f++;a=b.length;0<a&&(b[a-1]=1);return b};
zone.prototype.choseRandom=function(a){for(var c=Math.random(),d=0;d<a.length;d++)if(c<=a[d])return d;return 0};
zone.prototype.distinnct=function(){var a=[];if(2<=_admTrackRequest.balloon.length){for(var c=0,d=_admTrackRequest.balloon.length;c<d;c++)null!=_admTrackRequest.balloon[c].terms&&a.push(_admTrackRequest.balloon[c]);0<a.length&&(_admTrackRequest.balloon=a)}if(2<=_admTrackRequest.boxapp.length){a=[];c=0;for(d=_admTrackRequest.boxapp.length;c<d;c++)null!=_admTrackRequest.boxapp[c].terms&&a.push(_admTrackRequest.boxapp[c]);0<a.length&&(_admTrackRequest.boxapp=a)}};
zone.prototype.getBannerRun=function(a){var c=parseInt(ADS_CHECKER.getQuery("z")),d=parseInt(ADS_CHECKER.getQuery("bz")),b=parseInt(ADS_CHECKER.getQuery("z1")),f=parseInt(ADS_CHECKER.getQuery("bz1"));ADS_CHECKER.getStorage("_azs");var g=this.zoneid,l=this.style.slot,v=this.style.sort_banner_slot,z=!1,G=[],t=[],u=[],D=[],x=[],G=[],q=[],m=[],s=0,p={},e=!1,C=[],H=[],r=[],A=[],n=[];this.spamCpd=[];this.spamBidCpd=[];this.spamlstCp=[];this.slotHide=[];this.bz=0;b=isNaN(b)?0:b;f=isNaN(f)?0:f;c=isNaN(c)?
0:c;d=isNaN(d)?0:d;_admDefault[g].cpm=[];_admDefault[g].retar=[];for(var k=0;k<this.style.slot;k++){q[k]=[];m[k]=[];_admDefault[g][k]=[];_admDefault[g].cpm[k]=[];_admDefault[g].retar[k]=[];u[k]=0;if(0!=v[k+1])for(var h=0;h<v[k+1].length;h++)q[k][h]=[],m[k][h]=[],_admDefault[g][k][h]=[],_admDefault[g].cpm[k][h]=[],_admDefault[g].retar[k][h]=[];G[k]=[];t[k]=k+1;u[k]=0}ADS_City=""==ADS_City?0:ADS_City;var E=[],B=[],F=[],y="",K;for(K in a)if(h=new banner(a[K]),h.process(),a[K]=h,(9==h.bannertype||13==
h.bannertype)&&(1==h.tracking&&""==h.re)&&(y=h.src+"",y=y.match(/tvcpzone_[0-9]+/g))&&(y=y[0].replace(/tvcpzone_/g,""),""!=y&&(_admTrackRequest.balloon[_admTrackRequest.balloon.length]={zid:y,terms:h.terms,type:h.bannertype})),4==h.bannertype&&(1==h.tracking&&""==h.re)&&(y=h.src+"",y=y.match(/appzone_[0-9]+/g))&&(y=y[0].replace(/appzone_/g,""),""!=y&&_admTrackRequest.boxapp.push({zid:y,terms:h.terms,type:h.bannertype})),"101"==ADS_City&&!_chkPr&&h.bool&&-1!=h.location.indexOf(ADS_City)){y=ADS_CHECKER.getWeight(h.weight);
if(1<y)for(k=0;k<y;k++)E.push(h.bid+"_"+k);else E.push(h.bid);F.push({bid:h.bid,slotIdx:h.slotIdx,sort:h.sort,cpm:h.cpm});B.push(h.slotIdx)}this.distinnct();for(K in a)if(h=new banner(a[K]),"undefined"!=typeof a[K].bid){var y=parseInt(a[K].bid.toString()),I=a[K].slotIdx,J=ADS_CHECKER.getWeight(a[K].weight,ADS_Location);if(1==J||0==J)D.push(y);else if(d==y)D.push(y);else for(k=0;k<J;k++)D.push(y+"_"+k);h.process();!0!=h.bool||0==h.is_default&&-1==h.src.indexOf("ssvzone_")||(0!=h.is_default&&(h.bool=
!1),0===v[h.slotIdx]?_admDefault[g][h.slotIdx-1].push(h):v[h.slotIdx].length>=h.sort&&0<h.sort&&_admDefault[g][h.slotIdx-1][h.sort-1].push(h));!0==h.bool&&1==h.cpm&&(0===v[h.slotIdx]?16==h.bannertype?_admDefault[g].retar[h.slotIdx-1].push(h):_admDefault[g].cpm[h.slotIdx-1].push(h):v[h.slotIdx].length>=h.sort&&0<h.sort&&(16==h.bannertype?_admDefault[g].retar[h.slotIdx-1][h.sort-1].push(h):_admDefault[g].cpm[h.slotIdx-1][h.sort-1].push(h)));h.ckPr&&n.push(h.bid);z=!1;if(h.bool||h.bool&&(y==d&&g==c||
y==f&&g==b)){1===h.gr&&(H.push(h.bid),ADS_CHECKER.in_array(parseInt(h.cpname),A)||A.push(parseInt(h.cpname)),r.push({bid:h.bid,cid:parseInt(h.cpname),Idx:h.slotIdx,sort:h.sort}));var M=!1;if(0===J){var L=ADS_CHECKER.getStorage("_popup"),N="w"+h.bid.toString()+":",O=Math.floor((new Date).getTime()/1E3);if(""==L)M=!0,L=N+O.toString()+";";else{var P=ADS_CHECKER.subCookie(L,N,0);""==P?(M=!0,L+=N+O.toString()+";"):600<=O-parseInt(P.replace(N,""))&&(M=!0,L=L.replace(P+";",N+O.toString()+";"))}M&&ADS_CHECKER.setStorage("_popup",
L,10,"/")}z=z?z:y==d&&g==c||y==f&&g==b;s=y==d&&g==c||y==f&&g==b?I:s;this.bz=z?y:this.bz;!1===z&&(!0===M&&g!=c)&&(z=!0,s=I,this.bz=y);x.push(y);1<=parseInt(I)&&G[I-1].push(y);if(1==h.cpm)if(0<h.sort&&0!=v[I])if(1===J||0===J)q[I-1][h.sort-1].push(y);else if(this.bz==y)q[I-1][h.sort-1].push(y);else for(k=0;k<J;k++)q[I-1][h.sort-1].push(y+"_"+k);else{if(0==h.sort)if(1===J||0===J)q[I-1].push(y);else if(this.bz==y)q[I-1].push(y);else for(k=0;k<J;k++)q[I-1].push(y+"_"+k)}else if(8==h.bannertype&&(e||(e=
!0),p[h.bid]={bid:h.bid,slotIdx:h.slotIdx,sort:h.sort,weight:h.weight},ADS_CHECKER.in_array(h.slotIdx,C)||C.push(h.slotIdx)),0<h.sort&&0!=v[I])if(1===J||0===J)m[I-1][h.sort-1].push(y);else if(this.bz==y)m[I-1][h.sort-1].push(y);else for(k=0;k<J;k++)m[I-1][h.sort-1].push(y+"_"+k);else if(0==h.sort)if(1===J||0===J)m[I-1].push(y);else if(this.bz==y)m[I-1].push(y);else for(k=0;k<J;k++)m[I-1].push(y+"_"+k)}}if(0<n.length){if(0<_arNPr.length)for(k=0,c=_arNPr.length;k<c;k++)x=document.getElementById("ads_zone"+
_arNPr[k]),"undefined"!=typeof x&&null!=typeof x&&(x.style.display="none");for(var w=this.style.sort_banner_slot,x=n,k=0;k<l;k++)if(0==w[k+1])0<m[k].length&&(m[k]=ADS_CHECKER.array_duplicate(n,m[k])),0<q[k].length&&(q[k]=ADS_CHECKER.array_duplicate(n,q[k]));else for(h=0,d=w[k+1].length;h<d;h++)0<m[k][h].length&&(m[k][h]=ADS_CHECKER.array_duplicate(n,m[k][h])),0<q[k][h].length&&(q[k][h]=ADS_CHECKER.array_duplicate(n,q[k][h]))}else if(!_chkPr&&(_arNPr.push(g),0<E.length))if(n=this.style.slots_rotate,
null!=n){h=0;for(c=B.length;h<c;h++)if(0==v[B[h]])m[B[h]-1]=ADS_CHECKER.array_duplicate(E,m[B[h]-1]),q[B[h]-1]=ADS_CHECKER.array_duplicate(E,q[B[h]-1]);else for(w in F)ADS_CHECKER.in_array(F[w].slotIdx,[B[h]])&&(q[B[h]-1][F[w].sort-1]=ADS_CHECKER.array_duplicate(E,q[B[h]-1][F[w].sort-1]),m[B[h]-1][F[w].sort-1]=ADS_CHECKER.array_duplicate(E,m[B[h]-1][F[w].sort-1]));k=0;for(c=n.length;k<c;k++)if(b=ADS_CHECKER.array_duplicate(B,n[k]),0<b.length)for(h=0,d=n[k].length;h<d;h++)if(ADS_CHECKER.in_array(n[k][h],
b))if(0==v[n[k][h]])m[n[k][h]-1]=ADS_CHECKER.array_duplicate(E,m[n[k][h]-1]),q[n[k][h]-1]=ADS_CHECKER.array_duplicate(E,q[n[k][h]-1]);else for(w in F)ADS_CHECKER.in_array(F[w].slotIdx,b)&&(q[n[k][h]-1][F[w].sort-1]=ADS_CHECKER.array_duplicate(E,q[n[k][h]-1][F[w].sort-1]),m[n[k][h]-1][F[w].sort-1]=ADS_CHECKER.array_duplicate(E,m[n[k][h]-1][F[w].sort-1]));else if(0==v[n[k][h]])m[n[k][h]-1]=[],q[n[k][h]-1]=[];else for(w=0,l=v[n[k][h]].length;w<l;w++)q[n[k][h]-1][v[n[k][h]][w]-1]=[],m[n[k][h]-1][v[n[k][h]][w]-
1]=[]}else for(k=1;k<=l;k++)if(ADS_CHECKER.in_array(k,B))if(0==v[k])m[k-1]=ADS_CHECKER.array_duplicate(E,m[k-1]),q[k-1]=ADS_CHECKER.array_duplicate(E,q[k-1]);else for(w in F)F[w].slotIdx==k&&(q[k-1][F[w].sort-1]=ADS_CHECKER.array_duplicate(E,q[k-1][F[w].sort-1]),m[k-1][F[w].sort-1]=ADS_CHECKER.array_duplicate(E,m[k-1][F[w].sort-1]));this.spamCpd=H;this.spamBidCpd=r;this.spamlstCp=A;r=[];A=0;if(!z&&e&&0==H.length&&!_chkPr){e=this.style.slots_rotate;z=this.style.effect;for(k in p)if(r.push(p[k].bid),
2==z[p[k].slotIdx]&&(l=v[p[k].slotIdx],F=E=0,H=p[k].slotIdx,B=p[k].sort,0==q[H-1][B-1].length)){w=0;for(c=l.length;w<c;w++)l[w]==p[k].sort?F=m[H-1][B-1].length:E=Math.max(E,m[H-1][l[w]-1].length);if(F<E)for(c=E-F,w=0;w<c;w++)l=1!=c?"0_"+w:0,m[H-1][B-1].push(l),ADS_CHECKER.in_array(0,x)||x.push(0),ADS_CHECKER.in_array(l,D)||(A++,D.push(l),r.push(l))}H=t;if(null!=e)for(k=0,c=e.length;k<c;k++)if(w=ADS_CHECKER.array_duplicate(e[k],C),H=ADS_CHECKER.array_diff(H,e[k]),0<w.length){E=!1;h=0;for(d=e[k].length;h<
d;h++)if(2==z[e[k][h]])for(w=0,l=v[e[k][h]].length;w<l;w++){if(0<q[e[k][h]-1][w].length){E=!0;break}}else if(0<q[e[k][h]-1].length){E=!0;break}if(!E){h=B=0;for(d=e[k].length;h<d;h++)if(2==z[e[k][h]]){w=E=0;for(l=v[e[k][h]].length;w<l;w++)E=Math.max(E,m[e[k][h]-1][w].length);B+=E}else B+=m[e[k][h]-1].length;E=this.share-B;B=ADS_CHECKER.array_duplicate(e[k],C);if(0<B.length)for(F=Math.floor(Math.random()*B.length),w=0;w<E;w++){if(2==z[B[F]]){d=n=h=0;for(l=v[B[F]].length;d<l;d++)b=m[B[F]-1][d].length,
h=Math.max(h,b),h==b&&(n=d);l="0_"+A;m[B[F]-1][n].push(l)}else l="0_"+A,m[B[F]-1].push(l);ADS_CHECKER.in_array(0,x)||x.push(0);ADS_CHECKER.in_array(l,D)||(A++,D.push(l),r.push(l))}}}for(k in p)if(ADS_CHECKER.in_array(p[k].slotIdx,H))if(2==z[p[k].slotIdx]){if(0==q[p[k].slotIdx-1][p[k].sort-1].length)for(C=this.share-m[p[k].slotIdx-1][p[k].sort-1].length,w=0;w<C;w++)l="0_"+A,m[p[k].slotIdx-1][p[k].sort-1].push(l),ADS_CHECKER.in_array(0,x)||x.push(0),ADS_CHECKER.in_array(l,D)||(A++,D.push(l),r.push(l))}else if(0==
q[p[k].slotIdx-1].length)for(C=this.share-m[p[k].slotIdx-1].length,w=0;w<C;w++)l="0_"+A,m[p[k].slotIdx-1].push(l),ADS_CHECKER.in_array(0,x)||x.push(0),ADS_CHECKER.in_array(l,D)||(A++,D.push(l),r.push(l))}if(0==x.length)this.drawEmpty();else{this.abr=x;this.cpm=q;this.cpd=m;this.arrb=D;this.trk=0!=s?!0:!1;this.trks=s;this.arrSlot=t;this.arr7k=r;if(0<m.length){k=0;for(c=m.length;k<c;k++)if(0==v[k+1])u[k]=m[k].length;else for(h=0,d=v[k+1].length;h<d;h++)u[k]=Math.max(u[k],m[k][h].length);this.slotSize=
u}this.drawBannerRun(a)}};zone.prototype.resetParam=function(){1!=ADS_CHECKER.getQuery("admdebug")&&(this.style=this.arrSlot=this.cookie=this.html=null)};zone.prototype.renderIframe=function(a,c,d,b){return'<iframe src="" style="border:none;" width="'+d+'" height="'+b+'" marginheight="0" align="top" scrolling="No" frameborder="0" hspace="0" vspace="0" class="'+c+'" id="'+a+'"><html><head><style>body{margin:0;}</style></head><body></body></html></iframe>'};
zone.prototype.fillterCpdShow=function(a,c){var d=this.style.effect,b=this.spamBidCpd,f=this.cpd;ADS_CHECKER.in_array(a.bid,this.spamCpd)&&(ADS_CHECKER.in_array(parseInt(a.cpname),_arAdmShow)||_arAdmShow.push(parseInt(a.cpname)));if(2===d[a.slotIdx])for(var g=0,l=b.length;g<l;g++){b[g].Idx==a.slotIdx&&(b[g].cid==parseInt(a.cpname)&&b[g].sort>a.sort)&&(this.cpd[a.slotIdx-1][b[g].sort-1]=[b[g].bid]);if(0===a.gr&&a.slotIdx==b[g].Idx&&a.sort==b[g].sort||0===a.gr&&a.slotIdx!=b[g].Idx||1===a.gr&&a.slotIdx==
b[g].Idx&&a.sort==b[g].sort&&parseInt(a.cpname)!=b[g].cid||parseInt(a.cpname)!=b[g].cid&&b[g].Idx!=a.slotIdx&&0<c.length&&ADS_CHECKER.in_array(b[g].Idx,c))ADS_CHECKER.in_array(b[g].cid,_arAdmNotShow)||_arAdmNotShow.push(b[g].cid);if(a.slotIdx==b[g].Idx&&b[g].sort==a.sort||a.slotIdx==b[g].Idx&&ADS_CHECKER.in_array(b[g].cid,_arAdmNotShow))this.cpd[a.slotIdx-1][b[g].sort-1]=ADS_CHECKER.array_diff(f[a.slotIdx-1][b[g].sort-1],[b[g].bid])}else for(g=0,l=b.length;g<l;g++)if(b[g].Idx==a.slotIdx&&a.bid!=b[g].bid&&
!ADS_CHECKER.in_array(b[g].cid,_arAdmShow)||0<c.length&&b[g].Idx!=a.slotIdx&&ADS_CHECKER.in_array(b[g].Idx,c)&&!ADS_CHECKER.in_array(b[g].cid,_arAdmShow))ADS_CHECKER.in_array(b[g].cid,_arAdmNotShow)||_arAdmNotShow.push(b[g].cid);g=0;for(l=b.length;g<l;g++)ADS_CHECKER.in_array(b[g].cid,_arAdmNotShow)&&(2==d[b[g].Idx]?this.cpd[b[g].Idx-1][b[g].sort-1]=ADS_CHECKER.array_diff(this.cpd[b[g].Idx-1][b[g].sort-1],[b[g].bid]):this.cpd[b[g].Idx-1]=ADS_CHECKER.array_diff(this.cpd[b[g].Idx-1],[b[g].bid]))};
zone.prototype.drawBannerRun=function(a){var c=this.style.html,d=ADS_CHECKER.getStorage("_azs"),b=this.subCookie(d,"Ver:",0),f=this.style.slots_rotate,g=this.style.effect,l=this.arrSlot,v=this.style.sort_banner_slot,z=this.style.banner_default,G=this.share,t=this.zoneid,u=this.arrb,D=[];""==b&&(d="Ver:19;");this.cookie=d;var x=[];if(this.trk){if(0==v[this.trks])this.cpd[this.trks-1]=[this.bz];else for(var q=0,m=this.cpd[this.trks-1].length;q<m;q++)if(-1!=this.cpd[this.trks-1][q].indexOf(this.bz)||
-1!=this.cpm[this.trks-1][q].indexOf(this.bz)){this.cpd[this.trks-1][q]=[this.bz];break}if(f)for(var b=0,s=f.length;b<s;b++)l=ADS_CHECKER.array_diff(l,f[b]),-1!=f[b].indexOf(this.trks)?x.push(this.trks.toString()):(q=this.getSlotRun(t,b,f[b],d),d=this.cookie,q&&x.push(q.toString()))}else if(f)for(b=0,s=f.length;b<s;b++){l=ADS_CHECKER.array_diff(l,f[b]);if(q=this.getSlotRun(t,b,f[b],d))for(var d=ADS_CHECKER.array_diff(f[b],[parseInt(q.replace(/_[0-9]+/g,""))]),p=this.spamBidCpd.length,e=0;e<p;e++)ADS_CHECKER.in_array(this.spamBidCpd[e].Idx,
d)&&(ADS_CHECKER.in_array(this.spamBidCpd[e].cid,_arAdmNotShow)||_arAdmNotShow.push(this.spamBidCpd[e].cid));d=this.cookie;q&&x.push(q.toString())}for(var q=this.cpd,C=this.cpm,b=0;b<x.length;b++){var p=x[b].split("_"),H="";if(-1!=x[b].indexOf("m")){m=[];for(e=0;e<f[b].length;e++)if(2==g[f[b][e]]){for(var r=s=0;r<this.cpm[f[b][e]-1].length;r++)0<this.cpm[f[b][e]-1][r].length&&(s=Math.max(s,this.cpm[f[b][e]-1][r].length));if(0!=s)for(r=0;r<s;r++)m.push(f[b][e]+"_"+r)}else if(0<this.cpm[f[b][e]-1].length)for(r=
0;r<this.cpm[f[b][e]-1].length;r++)m.push(f[b][e]+"_"+r);e="z"+t+"m"+b+":";s=this.subCookie(d,e,0);if(""==s)0<m.length&&(r=ADS_CHECKER.rand(0,m.length-1),p[0]=m[r].replace(/_([0-9]+)/,""),d+=e+m[r]+";");else if(r=s.replace(e,"").split(","),0<ADS_CHECKER.array_diff(r,m).length&&0<m.length)r=ADS_CHECKER.rand(0,m.length-1),p[0]=m[r].replace(/_([0-9]+)/,""),d=d.replace(s+";",e+m[r]+";");else{var A=ADS_CHECKER.array_diff(m,r);0==A.length?1==m.length?p[0]=m[0].replace(/_([0-9]+)/,""):(e=this.strReverse(s.replace(e,
"")),1<e.split(",").length&&(p[0]=e.split(",")[0].replace(/_([0-9]+)/,""),d=d.replace(s+";","z"+t+"m"+b+":"+e+";"))):(r=ADS_CHECKER.rand(0,A.length-1),p[0]=A[r].replace(/_([0-9]+)/,""),d=d.replace(s+";",s+","+A[r]+";"))}}this.cookie=d;if(2==g[p[0]]){for(var n=s=0;n<v[p[0]].length;n++)s=Math.max(s,this.cpd[p[0]-1][n].length);for(n=0;n<v[p[0]].length;n++){A=[];r=[];for(e=0;e<q[p[0]-1][n].length;e++)A.push(ADS_CHECKER.in_array_position(q[p[0]-1][n][e],u));for(e=0;e<C[p[0]-1][n].length;e++)r.push(ADS_CHECKER.in_array_position(C[p[0]-
1][n][e],u));if(0<r.length&&A.length<s)for(e=0,m=A.length;e<s-m;e++)A.push("m"+(1<s-m?"_"+e:""));e="z"+t+"s"+p[0]+"_"+n+":";this.subCookie(d,e,0);m=!1;m=-1!=x[b].indexOf("m")?this.getMix(r,d,"z"+t+"sm"+p[0]+"_"+n+":"):this.getMix(A,d,"z"+t+"s"+p[0]+"_"+n+":");d=this.cookie;e="";!1===m||-1!=m.toString().indexOf("m")?0<r.length?(m=this.getMix(r,d,"z"+t+"sm"+p[0]+"_"+n+":"),d=this.cookie,r=0,r="string"==typeof u[m]?parseInt(u[m].replace(/_[0-9]/g,"")):u[m],e=new banner(a[r]),0<this.spamlstCp.length&&
0<this.spamBidCpd.length&&(this.fillterCpdShow(e,f[b]),q=this.cpd),1===e.iframe?(D.push(r),e=this.renderIframe("ads_zone"+t+"_banner"+e.bid,"banner"+(n+1),e.width,e.height)):e=e.renderBanner("ads_zone"+t+"_banner"+e.bid,t,Math.random(),"","banner"+(n+1))):(e=this.slotBannerDefault(p[0],n+1),""==e&&this.cpd[p[0]-1][n].length&&(m=ADS_CHECKER.in_array_position(q[p[0]-1][n][ADS_CHECKER.rand(0,this.cpd[p[0]-1][n].length-1)],u),r="string"==typeof u[m]?parseInt(u[m].replace(/_[0-9]/g,"")):u[m],e=new banner(a[r]),
0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,f[b]),q=this.cpd),1===e.iframe?(D.push(r),e=this.renderIframe("ads_zone"+t+"_banner"+e.bid,"banner"+(n+1),e.width,e.height)):e=e.renderBanner("ads_zone"+t+"_banner"+e.bid,t,Math.random(),"","banner"+(n+1)))):(r="string"==typeof u[m]?parseInt(u[m].replace(/_[0-9]/g,"")):u[m],0==r&&(e=ADS_CHECKER.array_diff(this.cpd[p[0]-1][n],this.arr7k),0!=e.length&&(1==e.length?r="string"==typeof e[0]?e[0].replace(/_[0-9]/g,""):e[0]:(m=Math.floor(Math.random()*
e.length-1),r="string"==typeof u[m]?e[m].replace(/_[0-9]/g,""):e[m]))),0!=r?(e=new banner(a[r]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,f[b]),q=this.cpd),1===e.iframe?(D.push(r),e=this.renderIframe("ads_zone"+t+"_banner"+e.bid,"banner"+(n+1),e.width,e.height)):e=e.renderBanner("ads_zone"+t+"_banner"+e.bid,t,Math.random(),"","banner"+(n+1))):e=this.slotBannerDefault(p[0],n+1));H+=e}c=""==H?c:c.replace("slot"+p[0]+"_content",H)}else if(A=[],r=[],e=parseInt(p[0]),!isNaN(e)){p[0]=
e;for(e=0;e<q[p[0]-1].length;e++)A.push(ADS_CHECKER.in_array_position(q[p[0]-1][e],u));for(e=0;e<C[p[0]-1].length;e++)r.push(ADS_CHECKER.in_array_position(C[p[0]-1][e],u));m=-1!=x[b].indexOf("m")?this.getMix(r,d,"z"+t+"sm"+p[0]+":"):this.getMix(A,d,"z"+t+"s"+p[0]+":");d=this.cookie;!1!==m?(r="string"==typeof u[m]?parseInt(u[m].replace(/_[0-9]/g,"")):u[m],0==r&&(e=ADS_CHECKER.array_diff(this.cpd[p[0]-1],this.arr7k),0!=e.length&&(1==e.length?r="string"==typeof e[0]?e[0].replace(/_[0-9]/g,""):e[0]:(m=
Math.floor(Math.random()*e.length-1),r="string"==typeof u[m]?e[m].replace(/_[0-9]/g,""):e[m]))),"undefined"==typeof r||isNaN(parseInt(r))||0==r?e=this.slotBannerDefault(p[0],"banner0"):(e=new banner(a[r]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,f[b]),q=this.cpd),1===e.iframe?(D.push(r),e=this.renderIframe("ads_zone"+t+"_banner"+e.bid,"banner0",e.width,e.height)):e=e.renderBanner("ads_zone"+t+"_banner"+e.bid,t,Math.random(),"","banner0"))):e=this.slotBannerDefault(p[0],
n+1);c=""==e?c:c.replace("slot"+p[0]+"_content",e)}}b=this.spamBidCpd;n=0;for(p=b.length;n<p;n++)ADS_CHECKER.in_array(b[n].cid,_arAdmNotShow)&&(2==g[b[n].Idx]?this.cpd[b[n].Idx-1][b[n].sort-1]=ADS_CHECKER.array_diff(this.cpd[b[n].Idx-1][b[n].sort-1],[b[n].bid]):this.cpd[b[n].Idx-1]=ADS_CHECKER.array_diff(this.cpd[b[n].Idx-1],[b[n].bid])),ADS_CHECKER.in_array(b[n].cid,_arAdmShow)&&(2==g[b[n].Idx]?this.cpd[b[n].Idx-1][b[n].sort-1]=[b[n].bid]:this.cpd[b[n].Idx-1]=[b[n].bid]);for(b=0;b<l.length;b++)if(p=
l[b].toString().split("_"),2==g[p[0]]){H="";for(n=0;n<v[p[0]].length;n++){A=[];r=[];m=[];for(e=0;e<q[p[0]-1][n].length;e++)A.push(ADS_CHECKER.in_array_position(q[p[0]-1][n][e],u));for(e=0;e<C[p[0]-1][n].length;e++)r.push(ADS_CHECKER.in_array_position(C[p[0]-1][n][e],u));m=A;if(0<C[l[b]-1].length||0<z[l[b]])if(s=G-q[l[b]-1][n].length,0<s&&0<C[l[b]-1][n].length)for(e=0;e<s;e++)m.push("m"+(1<s?"_"+e:""));e="z"+t+"s"+l[b]+"_"+n+":";this.subCookie(d,e,0);e=this.getMix(m,d,e);d=this.cookie;-1!=e.toString().indexOf("m")||
!1===e?0==C[p[0]-1][n].length?e=this.slotBannerDefault(p[0],n+1):(m=this.getMix(r,d,"z"+t+"sm"+n+":"),d=this.cookie,r="string"==typeof u[m]?parseInt(u[m].replace(/_[0-9]/g,"")):u[m],e=new banner(a[r]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,[]),q=this.cpd),1===e.iframe?(D.push(r),e=this.renderIframe("ads_zone"+t+"_banner"+e.bid,"banner"+(n+1),e.width,e.height)):e=e.renderBanner("ads_zone"+t+"_banner"+e.bid,t,Math.random(),"","banner"+(n+1))):(r="string"==typeof u[e]?
parseInt(u[e].replace(/_[0-9]/g,"")):u[e],0==r&&(e=ADS_CHECKER.array_diff(this.cpd[p[0]-1][n],this.arr7k),0!=e.length&&(1==e.length?r="string"==typeof e[0]?e[0].replace(/_[0-9]/g,""):e[0]:(m=Math.floor(Math.random()*e.length-1),r="string"==typeof u[m]?e[m].replace(/_[0-9]/g,""):e[m]))),0!=r?(e=new banner(a[r]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,[]),q=this.cpd),1===e.iframe?(D.push(r),e=this.renderIframe("ads_zone"+t+"_banner"+e.bid,"banner"+(n+1),e.width,e.height)):
e=e.renderBanner("ads_zone"+t+"_banner"+e.bid,t,Math.random(),"","banner"+(n+1))):e=this.slotBannerDefault(p[0],n+1));H+=e}c=""==H?c:c.replace("slot"+l[b]+"_content",H)}else{A=[];r=[];for(e=0;e<q[l[b]-1].length;e++)A.push(ADS_CHECKER.in_array_position(q[l[b]-1][e],u));for(e=0;e<C[l[b]-1].length;e++)r.push(ADS_CHECKER.in_array_position(C[l[b]-1][e],u));m=A;if(0<C[l[b]-1].length||0<z[l[b]])for(s=G-q[l[b]-1].length,e=0;e<s;e++)m.push("m"+(1<s?"_"+e:""));e="z"+t+"s"+l[b]+":";this.subCookie(d,e,0);e=this.getMix(m,
d,e);d=this.cookie;-1!=e.toString().indexOf("m")||!1===e?0!=C[l[b]-1].length?(m=this.getMix(r,d,"z"+t+"sm"+l[b]+":"),d=this.cookie,r="string"==typeof u[m]?parseInt(u[m].replace(/_[0-9]/g,"")):u[m],e=new banner(a[r]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,[]),q=this.cpd),1===e.iframe?(D.push(r),e=this.renderIframe("ads_zone"+t+"_banner"+e.bid,"banner0",e.width,e.height)):e=e.renderBanner("ads_zone"+t+"_banner"+e.bid,t,Math.random(),"","banner0")):e=this.slotBannerDefault(l[b],
0):(r="string"==typeof u[e]?parseInt(u[e].replace(/_[0-9]/g,"")):u[e],0==r&&(e=ADS_CHECKER.array_diff(this.cpd[p[0]-1],this.arr7k),0!=e.length&&(1==e.length?r="string"==typeof e[0]?e[0].replace(/_[0-9]/g,""):e[0]:(m=Math.floor(Math.random()*e.length-1),r="string"==typeof u[m]?e[m].replace(/_[0-9]/g,""):e[m]))),0!=r?(e=new banner(a[r]),0<this.spamlstCp.length&&0<this.spamBidCpd.length&&(this.fillterCpdShow(e,[]),q=this.cpd),1===e.iframe?(D.push(r),e=this.renderIframe("ads_zone"+t+"_banner"+e.bid,"banner0",
e.width,e.height)):e=e.renderBanner("ads_zone"+t+"_banner"+e.bid,t,Math.random(),"","banner0")):e=this.slotBannerDefault(l[b],"banner0"));c=""==e?c:c.replace("slot"+l[b]+"_content",e)}if(f){l=[];b=0;for(s=x.length;b<s;b++)e=x[b].replace(/_([a-z0-9]+)/gi,""),l.push(e);b=0;for(s=f.length;b<s;b++)if(v=ADS_CHECKER.array_duplicate(f[b],l),0==v.length){v=[];q=0;for(m=f[b].length;q<m;q++)2!=g[f[b][q]]&&(0<_admDefault[t][f[b][q]-1].length||0!=z[f[b][q]])&&v.push(f[b][q]);0<v.length&&(v=v[Math.floor(Math.random()*
v.length)],e=this.slotBannerDefault(v,"banner0"),c=c.replace("slot"+v+"_content",e))}}c=this.changeHtml(c);document.write(c);this.hideSlotNone();ADS_CHECKER.setStorage("_azs",d,"","/");0!=this.trks&&(c=ADS_CHECKER.getElementTop("ads_zone"+t+"_slot"+this.trks),0<c&&window.scrollTo(0,c));b=0;for(m=D.length;b<m;b++)c=document.getElementById("ads_zone"+t+"_banner"+D[b]),e=new banner(a[D[b]]),c=c.contentWindow?c.contentWindow.document:c.contentDocument?c.contentDocument:c.document,f="<html><head><style>body{margin:0}</style></head><body>"+
e.renderBanner("ads_zone"+t+"_banner"+D[b],t,Math.random(),"","banner"+e.sort)+"</body></html>",c.write(f),c.close()};
zone.prototype.getMix=function(a,c,d){var b=!1;if(0==a.length)return!1;if(1==a.length)return a[0];var f=this.subCookie(c,d,0),g=f.replace(d,"").split(","),l=ADS_CHECKER.array_diff(g,a),g=ADS_CHECKER.array_diff(a,g);""==f?0<a.length&&(b=ADS_CHECKER.rand(0,a.length-1),b=a[b],c+=d+b+";"):0<l.length?(c=c.replace(f+";",""),0<a.length&&(b=ADS_CHECKER.rand(0,a.length-1),b=a[b],c+=d+b+";")):0<g.length?(b=ADS_CHECKER.rand(0,g.length-1),b=g[b],c=c.replace(f+";",f+","+b+";")):(a=this.strReverse(f.replace(d,
"")),b=a.split(",")[0],c=c.replace(f+";",d+a+";"));this.cookie=c;return b};
zone.prototype.getSlotRun=function(a,c,d,b){this.subCookie(b,"Ver:",0);var f=this.style.effect,g=this.style.sort_banner_slot,l=this.style.banner_default,v=[],z=[],G=this.share,t=!1,u=[],D=[],x=this.spamBidCpd,f=this.style.effect,q=x.length,m=[];if(0<q)for(c=0;c<q;c++)ADS_CHECKER.in_array(x[c].cid,_arAdmShow)&&(ADS_CHECKER.in_array(x[c].Idx,m)||m.push(x[c].Idx),0==f[x[c].Idx]?(this.cpd[x[c].Idx-1]=[x[c].bid],this.cpm[x[c].Idx-1]=[]):0<x[c].sort&&(this.cpd[x[c].Idx-1][x[c].sort-1]=[x[c].bid],this.cpm[x[c].Idx-
1][x[c].sort-1]=[]));0<m.length&&(d=m);q=x=0;for(m=d.length;q<m;q++){var s=this.cpd[d[q]-1].join(",").replace(/,/g,""),p=this.cpm[d[q]-1].join(",").replace(/,/g,"");if(""!=s){z.push(d[q]);var e=0;if(2==f[d[q]])for(s=0;s<g[d[q]].length;s++)e=Math.max(e,this.cpd[d[q]-1][s].length);else e=this.cpd[d[q]-1].length;for(s=0;s<e;s++)u.push(d[q]+(1<e?"_"+s:""));x+=e}if(""!=p){p=0;v.push(d[q]);if(2==f[d[q]])for(s=0;s<g[d[q]].length;s++)p=Math.max(p,this.cpm[d[q]-1][s].length);else p=this.cpm[d[q]-1].length;
for(s=0;s<p;s++)D.push(d[q]+(1<p?"_"+s:""))}if(q==m-1)if(p=this.subCookie(b,"z"+a+"R"+c+":",0),0<x){e=u;if(0<v.length)for(s=0;s<G-x;s++)u.push(d[q]+"_m_"+s);var C=p.replace("z"+a+"R"+c+":","").split(",");1==u.length||""==p||C.length>u.length||0!=ADS_CHECKER.array_diff(C,u).length?(""!=p&&(b=b.replace(p+";","")),s=ADS_CHECKER.rand(0,e.length-1),t=e[s],1<u.length&&(b+="z"+a+"R"+c+":"+e[s]+";")):C.length==u.length&&0==ADS_CHECKER.array_diff(C,u).length&&0==ADS_CHECKER.array_diff(u,C).length?(t=this.strReverse(p.replace("z"+
a+"R"+c+":","")),s=t.split(","),b=b.replace(p+";","z"+a+"R"+c+":"+t+";"),-1!=s[0].indexOf("m")?(b=this.choseMix(a,c,D,b),t=b+"_m",b=this.cookie):t=s[0]):""==p?(s=ADS_CHECKER.rand(0,e.length-1),t=e[s],b+="z"+a+"R"+c+":"+e[s]+";"):(s=ADS_CHECKER.array_diff(C,e),t=ADS_CHECKER.array_diff(u,C),e=ADS_CHECKER.array_diff(e,C),0==s.length&&0!=e.length?(s=ADS_CHECKER.rand(0,e.length-1),b=b.replace(p+";",p+","+e[s]+";"),t=e[s]):(s=ADS_CHECKER.rand(0,t.length-1),b=b.replace(p+";",p+","+t[s]+";"),t=b=this.choseMix(a,
c,D,b),b=this.cookie))}else if(0==x&&0<v.length)b=this.choseMix(a,c,D,b),t=b+"_m",b=this.cookie;else if(0==x&&0==v.length){p=[];s=0;for(e=d.length;s<e;s++)0!=l[d[s]]&&p.push(d[s]);0<p.length&&(t=p[ADS_CHECKER.rand(0,p.length-1)]+"_d")}}this.cookie=b;return t};
zone.prototype.choseMix=function(a,c,d,b){var f=this.subCookie(b,"z"+a+"m"+c+":",0);if(1==d.length)return""!=f&&(b=b.replace(f+";","")),this.cookie=b,d[0];var g=f.replace("z"+a+"m"+c+":","").split(",");if(g.length>d.length||""!=g[0]&&0!=ADS_CHECKER.array_diff(g,d).length)return""!=f&&(b=b.replace(f+";","")),this.cookie=b,d[ADS_CHECKER.rand(0,d.length-1)];if(g.length==d.length&&0==ADS_CHECKER.array_diff(g,d).length&&0==ADS_CHECKER.array_diff(d,g).length)return d=this.strReverse(f.replace("z"+a+"m"+
c+":","")),g=d.split(","),this.cookie=b=b.replace(f+";","z"+a+"m"+c+":"+d+";"),g[0];d=ADS_CHECKER.array_diff(d,g);g=ADS_CHECKER.rand(0,d.length-1);this.cookie=b=""!=f?b.replace(f+";",f+","+d[g]+";"):b+("z"+a+"m"+c+":"+d[g]+";");return d[g]};
zone.prototype.drawEmpty=function(a){a=[];for(var c=this.style.slots_rotate,d=this.style.effect,b=this.style.html,f=this.style.banner_default,g=this.zoneid,l=0;l<this.style.slot;l++)a[l]=l+1;if(c)for(var l=0,v=c.length;l<v;l++){a=ADS_CHECKER.array_diff(a,c[l]);for(var z=[],G=0,t=c[l].length;G<t;G++){var u=!1;2!=d[c[l][G]]&&0<_admDefault[g][c[l][G]-1].length&&(z.push(c[l][G]),u=!0);0!=f[c[l][G]]&&!1===u&&z.push(c[l][G])}0<z.length&&a.push(z[ADS_CHECKER.rand(0,z.length-1)])}l=0;for(v=a.length;l<v;l++)c=
2!=d[a[l]]?this.slotBannerDefault(a[l],0):this.slotAllDefault(a[l]),b=""==c?b:b.replace("slot"+a[l]+"_content",c);b=this.removeHtml(b);document.write(b)};zone.prototype.initZone=function(a,c){a?this.getBannerRun(a):this.drawEmpty();return!1};
zone.prototype.slotBannerDefault=function(a,c){var d=this.style.effect;if(2!=d[a]&&(0===c||"banner0"==c)){if(0<_admDefault[this.zoneid][a-1].length)return d=Math.floor(_admDefault[this.zoneid][a-1].length*Math.random()),d=new banner(_admDefault[this.zoneid][a-1][d]),d.renderBanner("ads_zone"+this.zoneid+"_banner"+c,this.zoneid,Math.random(),"","banner"+c)}else if(2===d[a]&&0<_admDefault[this.zoneid][a-1][c-1].length)return d=Math.floor(_admDefault[this.zoneid][a-1][c-1].length*Math.random()),d=new banner(_admDefault[this.zoneid][a-
1][c-1][d]),d.renderBanner("ads_zone"+this.zoneid+"_banner"+c,this.zoneid,Math.random(),"","banner"+c);return 0!=this.style.banner_default[a]&&(d=this.style.banner_default[a],d=new banner({bannertype:0,bid:0,title:"",type:d.type,link:d.link,src:d.src,width:d.width,height:d.height,created:null,expired:null,slotIdx:a,attr:null,terms:d.terms,clicks:0,views:0,cpname:"",counter:!1,iframe:0,fix_ie:0,sort:0,link_clicks:null,link_views:null}),d.process(),d.bool)?d.renderBanner("ads_zone"+this.zoneid+"_banner"+
c,this.zoneid,Math.random(),"","banner"+c):""};zone.prototype.slotAllDefault=function(a){for(var c=this.style.sort_banner_slot[a].length,d="",b=0;b<c;b++)d+=this.slotBannerDefault(a,b+1);return d};zone.prototype.subCookie=function(a,c,d){c=a.indexOf(c,d);d=a.length-1;if(-1!=c){var b=a.indexOf(";",c);-1==b&&(b=d);return a.substring(c,b)}return""};zone.prototype.strReverse=function(a){var c=a.indexOf(","),d=a.length;return-1==c?a:a.substring(c+1,d)+","+a.substring(0,c)};
zone.prototype.addBanners=function(a){var c=this.style.slot,d='<div id="ads_zone'+this.zoneid+'">'+this.style.html.replace(/id="slot/g,'id="ads_zone'+this.zoneid+"_slot")+"</div>";this.style.html='<div id="ads_zone'+this.zoneid+'">'+this.style.html.replace(/id="slot/g,'id="ads_zone'+this.zoneid+"_slot")+"</div>";this.style.css&&this.bindCSS(this.style.css);if(this.style&&0<this.style.slot){this.slots=[];for(var b=0;b<=c;b++)this.slots[b]=""}if(!this.initZone(a,d))return!1};
zone.prototype.getSizeStr=function(){this.width=0<parseInt(this.width)?"width:"+this.width+"px;":"";this.height=0<parseInt(this.height)?"height:"+this.height+"px;":""};zone.prototype.getZoneTag=function(){return"ads_zone"+this.zoneid};zone.prototype.append2slot=function(a,c){var d="slot"+c+"_content";this.style.html=this.style.html.replace(d,a+d)};zone.prototype.drawZoneTag=function(){};zone.prototype.hideEmptyZone=function(a){};
zone.prototype.bindCSS=function(a){var c=document.createElement("style");c.type="text/css";document.getElementsByTagName("head")[0].appendChild(c);c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a))};



function _admMd5(p){var h=function(a,b){var c,d,f,e,g;f=a&2147483648;e=b&2147483648;c=a&1073741824;d=b&1073741824;g=(a&1073741823)+(b&1073741823);return c&d?g^2147483648^f^e:c|d?g&1073741824?g^3221225472^f^e:g^1073741824^f^e:g^f^e},k=function(a,b,c,d,f,e,g){a=h(a,h(h(b&c|~b&d,f),g));return h(a<<e|a>>>32-e,b)},l=function(a,b,c,d,f,e,g){a=h(a,h(h(b&d|c&~d,f),g));return h(a<<e|a>>>32-e,b)},m=function(a,b,d,c,e,f,g){a=h(a,h(h(b^d^c,e),g));return h(a<<f|a>>>32-f,b)},n=function(a,b,d,c,f,e,g){a=h(a,h(h(d^
(b|~c),f),g));return h(a<<e|a>>>32-e,b)},q=function(a){var b="",d="",c;for(c=0;3>=c;c++)d=a>>>8*c&255,d="0"+d.toString(16),b+=d.substr(d.length-2,2);return b},e=[],f,r,s,t,u,a,b,c,d;p=function(a){a=a.replace(/\r\n/g,"\n");for(var b="",d=0;d<a.length;d++){var c=a.charCodeAt(d);128>c?b+=String.fromCharCode(c):(127<c&&2048>c?b+=String.fromCharCode(c>>6|192):(b+=String.fromCharCode(c>>12|224),b+=String.fromCharCode(c>>6&63|128)),b+=String.fromCharCode(c&63|128))}return b}(p);e=function(b){var a,c=b.length;
a=c+8;for(var d=16*((a-a%64)/64+1),e=Array(d-1),f=0,g=0;g<c;)a=(g-g%4)/4,f=8*(g%4),e[a]|=b.charCodeAt(g)<<f,g++;a=(g-g%4)/4;e[a]|=128<<8*(g%4);e[d-2]=c<<3;e[d-1]=c>>>29;return e}(p);a=1732584193;b=4023233417;c=2562383102;d=271733878;p=e.length;for(f=0;f<p;f+=16)r=a,s=b,t=c,u=d,a=k(a,b,c,d,e[f+0],7,3614090360),d=k(d,a,b,c,e[f+1],12,3905402710),c=k(c,d,a,b,e[f+2],17,606105819),b=k(b,c,d,a,e[f+3],22,3250441966),a=k(a,b,c,d,e[f+4],7,4118548399),d=k(d,a,b,c,e[f+5],12,1200080426),c=k(c,d,a,b,e[f+6],17,
2821735955),b=k(b,c,d,a,e[f+7],22,4249261313),a=k(a,b,c,d,e[f+8],7,1770035416),d=k(d,a,b,c,e[f+9],12,2336552879),c=k(c,d,a,b,e[f+10],17,4294925233),b=k(b,c,d,a,e[f+11],22,2304563134),a=k(a,b,c,d,e[f+12],7,1804603682),d=k(d,a,b,c,e[f+13],12,4254626195),c=k(c,d,a,b,e[f+14],17,2792965006),b=k(b,c,d,a,e[f+15],22,1236535329),a=l(a,b,c,d,e[f+1],5,4129170786),d=l(d,a,b,c,e[f+6],9,3225465664),c=l(c,d,a,b,e[f+11],14,643717713),b=l(b,c,d,a,e[f+0],20,3921069994),a=l(a,b,c,d,e[f+5],5,3593408605),d=l(d,a,b,c,
e[f+10],9,38016083),c=l(c,d,a,b,e[f+15],14,3634488961),b=l(b,c,d,a,e[f+4],20,3889429448),a=l(a,b,c,d,e[f+9],5,568446438),d=l(d,a,b,c,e[f+14],9,3275163606),c=l(c,d,a,b,e[f+3],14,4107603335),b=l(b,c,d,a,e[f+8],20,1163531501),a=l(a,b,c,d,e[f+13],5,2850285829),d=l(d,a,b,c,e[f+2],9,4243563512),c=l(c,d,a,b,e[f+7],14,1735328473),b=l(b,c,d,a,e[f+12],20,2368359562),a=m(a,b,c,d,e[f+5],4,4294588738),d=m(d,a,b,c,e[f+8],11,2272392833),c=m(c,d,a,b,e[f+11],16,1839030562),b=m(b,c,d,a,e[f+14],23,4259657740),a=m(a,
b,c,d,e[f+1],4,2763975236),d=m(d,a,b,c,e[f+4],11,1272893353),c=m(c,d,a,b,e[f+7],16,4139469664),b=m(b,c,d,a,e[f+10],23,3200236656),a=m(a,b,c,d,e[f+13],4,681279174),d=m(d,a,b,c,e[f+0],11,3936430074),c=m(c,d,a,b,e[f+3],16,3572445317),b=m(b,c,d,a,e[f+6],23,76029189),a=m(a,b,c,d,e[f+9],4,3654602809),d=m(d,a,b,c,e[f+12],11,3873151461),c=m(c,d,a,b,e[f+15],16,530742520),b=m(b,c,d,a,e[f+2],23,3299628645),a=n(a,b,c,d,e[f+0],6,4096336452),d=n(d,a,b,c,e[f+7],10,1126891415),c=n(c,d,a,b,e[f+14],15,2878612391),
b=n(b,c,d,a,e[f+5],21,4237533241),a=n(a,b,c,d,e[f+12],6,1700485571),d=n(d,a,b,c,e[f+3],10,2399980690),c=n(c,d,a,b,e[f+10],15,4293915773),b=n(b,c,d,a,e[f+1],21,2240044497),a=n(a,b,c,d,e[f+8],6,1873313359),d=n(d,a,b,c,e[f+15],10,4264355552),c=n(c,d,a,b,e[f+6],15,2734768916),b=n(b,c,d,a,e[f+13],21,1309151649),a=n(a,b,c,d,e[f+4],6,4149444226),d=n(d,a,b,c,e[f+11],10,3174756917),c=n(c,d,a,b,e[f+2],15,718787259),b=n(b,c,d,a,e[f+9],21,3951481745),a=h(a,r),b=h(b,s),c=h(c,t),d=h(d,u);return(q(a)+q(b)+q(c)+
q(d)).toLowerCase()}


if(ADS_Location=='3'){
	imgHost=imgHost.replace("admicro2.","admicro2-hcm.");
	admImgHost=true;
}


var _admTVCVideo=[];
function admParamTvc(){var a=0,b=0;1==ADS_CHECKER.getQuery("admdebug")&&console.log(_admTVCVideo);void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(a=ADS_CHECKER.getQuery("_itvc"),a=""==a?0:parseInt(a),b=ADS_CHECKER.getCookie("__R"),b=""==b?0:parseInt(b));0<_admTVCVideo.length&&(a=0);0<arguments.length&&0!=a&&_admTVCVideo.push(a);return a+";"+b+";"+(""==ADS_Age?0:ADS_Age)+";0"};


(function(){var d=!1,c=[];if(!(window.AdmonDomReady&&"function"==typeof window.AdmonDomReady)){var a=function(){if(!document.body)return setTimeout(a,13);for(var b=0;b<c.length;b++)c[b]();c=[]};window.AdmonDomReady=function(b){c.push(b);if("complete"==document.readyState)a();else if(!d){if(document.addEventListener){var e=function(){document.removeEventListener("DOMContentLoaded",e,!1);a()};document.addEventListener("DOMContentLoaded",e,!1);window.addEventListener("load",a,!1)}else if(document.attachEvent){var f=
function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())};document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);b=!1;try{b=null==window.frameElement}catch(h){}if(document.documentElement.doScroll&&b){var g=function(){if(0!=c.length){try{document.documentElement.doScroll("left")}catch(b){setTimeout(g,1);return}a()}};g()}}d=!0}}}})();
function admaddEventListener(d,c,a){"addEventListener"in d?d.addEventListener(c,a):"attachEvent"in d&&d.attachEvent("on"+c,a)};


var jsTimeout=new Number,jsTimeDelay=60,jsAcceleration=0.2,jsVelocity=3;function jsAnimate(a,d,c){var b=new Number,b=[],b=String(document.getElementById(a).style[d]).split("px"),b=parseInt(b[0]);clearTimeout(jsTimeout);parseInt(c)>b?jsTimeout=setTimeout('animateProcess("'+a+'", "'+d+'", "increase", "'+b+'", "'+c+'", 1)',jsTimeDelay):parseInt(c)<b&&(jsTimeout=setTimeout('animateProcess("'+a+'", "'+d+'", "increase", "'+b+'", "'+c+'", 1)',jsTimeDelay))}
function animateProcess(a,d,c,b,f,g){clearTimeout(jsTimeout);var h=jsAcceleration*Math.pow(parseInt(g),2)/2+jsVelocity*parseInt(g),e=new Number;switch(c){case "increase":e=parseInt(b)+parseInt(h);e>=parseInt(f)?document.getElementById(a).style[d]=f+"px":(document.getElementById(a).style[d]=e+"px",g++,jsTimeout=setTimeout('animateProcess("'+a+'", "'+d+'", "'+c+'", "'+e+'", "'+f+'", '+g+")",jsTimeDelay));break;case "decrease":e=parseInt(b)-parseInt(h),e<=parseInt(f)?document.getElementById(a).style[d]=
f+"px":(document.getElementById(a).style[d]=e+"px",g++,jsTimeout=setTimeout('animateProcess("'+a+'", "'+d+'", "'+c+'", "'+e+'", "'+f+'", '+g+")",jsTimeDelay))}}function hookExpand(a,d,c){a=document.getElementById(a);if(null!=a){if(c){for(var c=a.offsetTop,b=a;b.offsetParent&&b.offsetParent!=document.body;)b=b.offsetParent,c+=b.offsetTop;window.scrollTo(0,c)}a.style.clip=d}};


var _arrCpmRun=[0],_arrCpm=[0];function cpmzone(a){this.zid=a;this.banIframe=[]}
cpmzone.prototype.renderIframe=function(){for(var a=this.banIframe,c=0,d=a.length;c<d;c++){var b=document.getElementById("cpmzone_"+this.zid+"_"+c+"_"+a[c].bid),b=b.contentWindow?b.contentWindow.document:b.contentDocument?b.contentDocument:b.document;b.write("<head><style>body{margin:0}</style></head><body>"+('<script type="text/javascript">function admGetUrlCk(){return \''+a[c].click+"';}function cpmtkc(){var img=new Image(); img.src='"+a[c].click+"';}\x3c/script>")+a[c].src)+"</body>";b.close()}};
cpmzone.prototype.logging=function(a,c,d){var b="http://",e="";c?(b+="logging.admicro.vn/_adv.gif",e=d?encodeURIComponent(b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1"):b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1"):(b+="c.logging.admicro.vn/_adc.html",e=d?encodeURIComponent(b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+
(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1&adm_rehttp="+escape(a.link)+("undefined"!=typeof a.cpa&&1==a.cpa?"&adc_cpa=1":"")):b+"?adm_domain="+escape(document.URL)+"&adm_campaign="+(a.cid?a.cid:"")+"&adm_aditem="+a.bid+"&adm_zoneid="+this.zid+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(a.link)+("undefined"!=typeof a.cpa&&1==a.cpa?"&adc_cpa=1":""));return e};
cpmzone.prototype.renderBanner=function(a){var c="";switch(a.type){case "gif":case "jpeg":case "png":case "jpg":c+=this.renderBannerImage(a);break;case "swf":var d=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(d=ADS_CHECKER.flash);d?c+=this.renderBannerFlash(a):(a.src=a.src_bk,c+=this.renderBannerImage(a));break;case "html":c+=a.src;break;case "iframe":d=this.banIframe.length,this.banIframe[d]={src:a.src,bid:a.bid,click:this.logging(a,!1,!1).replace(/&adm_rehttp=(.*)$/,"&adm_rehttp=")},
c+='<iframe style="border:none;" marginheight="0" align="top" scrolling="No" frameborder="0" hspace="0" vspace="0" id="cpmzone_'+this.zid+"_"+d+"_"+a.bid+'" width="'+a.width+'" height="'+a.height+'" ></iframe>'}document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>';return c+this.renderLinkViews(a.link_views)};
cpmzone.prototype.renderLinkViews=function(a){var c="";null!=a&&(document.images?(new Image).src=a:c+='<div style="position:absolute;background:url('+a+');height:0; width:0" ><span style="height:0; width:0"></span></div>');return c};
cpmzone.prototype.renderBannerImage=function(a){var c='<img border="0" id="cpm'+this.zid+'" src="'+(admImgHost?a.src.replace("admicro2.","admicro2-hcm."):a.src)+'"'+(a.width?' width="'+a.width+'"':"")+(a.height?' height="'+a.height+'"':""),c=c+"  />";return a.link?'<a href="'+this.logging(a,!1,!1)+'" target="_blank">'+c+"</a>":c};
cpmzone.prototype.renderBannerFlash=function(a){var c="",d=a.link?"alink1="+this.logging(a,!1,!0)+"&amp;atar1=_blank":"";""!=d&&(c+=' flashvars="'+d+'"');return'<embed  src="'+(admImgHost?a.src.replace("admicro2.","admicro2-hcm."):a.src)+'" height="'+a.height+'" align="middle" width="'+a.width+'" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" '+c+' allowscriptaccess="always" wmode="transparent" quality="high" />'};
cpmzone.prototype.getData=function(a){var c=[],d=0,b=0,e="",h="",f=","+_arrCpmRun.join(",")+",",n=-1,l="",k=[],p=[],q=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(q=ADS_CHECKER.flash,d=parseInt(ADS_CHECKER.getQuery("i")),e=ADS_CHECKER.getCookie("__R"),h=ADS_CHECKER.getCookie("__RC"));for(var e=","+e+",",h=","+h+",",d=isNaN(d)?0:d,g=0,r=a.length;g<r;g++){var m=!1;if(-1==f.indexOf(","+a[g].bid+",")){var m=","+a[g].l+",",s=/,[1|2|3],[1|2|3],[1|2|3],/g,m=-1!=m.indexOf(",,")||-1!=m.indexOf(",0,")||
s.test(m)||-1!=m.indexOf(e)||-1!=m.indexOf(h);q||"swf"==a[g].type&&""==a[g].src_bk&&(m=!1);"undefined"!=typeof __arCPM4K&&void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&ADS_CHECKER.in_array(a[g].bid,__arCPM4K)&&(203384!=a[g].bid&&204368!=a[g].bid&&191479!=a[g].bid&&192146!=a[g].bid&&197484!=a[g].bid)&&(m=!1);d==a[g].bid&&(m=!0);m&&(b=d==a[g].bid?a[g].bid:b,n=d==a[g].bid?g:n,l=d==a[g].bid?a[g].width+"x"+a[g].height:l,c.push(g),1==this.db&&(300==a[g].width&&250==a[g].height||468==a[g].width&&
90==a[g].height)?g!=n&&k.push(g):1==this.db&&(300==a[g].width&&600==a[g].height||980==a[g].width&&90==a[g].height)&&p.push(g))}}if(0==c.length)return c;this.bz=b;if(1==this.db&&1<c.length){if("980x90"==l||"300x600"==l)return[n];if("300x250"==l||"468x90"==l)return 2>=k.length?k:[b,k[Math.floor(k.length*Math.random())]];if("980x90"==this.size||"300x600"==this.size){if(0<k.length&&0<p.length)return 0.5<=Math.random()?k:p;if(0<k.length)return k;if(0<p.length)return p}}else return 0!=b?[n]:c};
cpmzone.prototype.renderBannerExp=function(a){var c="";switch(a.type){case "gif":case "jpeg":case "png":case "jpg":case "swf":var d=!0;void 0!=window.ADS_CHECKER&&"undefined"!=window.ADS_CHECKER&&(d=ADS_CHECKER.flash);d?(c+=this.renderBannerFlashExp(a),document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>'):("swf"==a.type&&(a.src=a.src_bk),c+=this.renderBannerImage(a));
break;case "html":c+=a.src,document.images?(new Image).src=this.logging(a,!0,!1):c+='<div style="background:url('+this.logging(a,!0,!1)+'); height:0; width:0;position:absolute;border:none" ><span style="height:0; width:0"></span></div>'}c+=this.renderLinkViews(a.link_views);d="";if("300"==a.width)return d='<div id="rick_banner'+a.bid+'_1" style="position: relative; width: 300px; height: 250px;"><div id="rick_banner'+a.bid+'" style="position: absolute;top: 0px; right: 0px; clip: rect(0px, 980px, 250px, 680px); z-index: 1000;">',
d+c+"</div></div>";d="468";"980"==a.width&&(d="0");d='<div id="rick_banner'+a.bid+'" style="position: relative; height:'+a.height+"px;  width:"+a.width+"px;  bottom: 0px; right: 0px; clip: rect(0px, 980px, 90px, "+d+'px); z-index: 1000;">';return d+c+"</div>"};
cpmzone.prototype.renderBannerFlashExp=function(a){var c="",d=a.link?"alink1="+this.logging(a,!1,!0)+"&amp;atar1=_blank":"",b="rick_banner"+a.bid;""!=d&&(c+=' flashvars="div_id='+b+"&"+d+"&file1="+a.src+"&file2="+a.src_exp+"&size="+a.width+"x"+a.height+'"');d=3;"300"==a.width&&(d=7);return'<embed height="300" align="middle" width="980" quality="high" wmode="transparent" allowscriptaccess="always" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" '+c+' src="http://corejs.com/cpm(7k-4k)/expand7k_v1.swf?v='+
d+'"/>'};cpmzone.prototype.Shuffle=function(a){for(var c,d,b=a.length;b;c=parseInt(Math.random()*b),d=a[--b],a[b]=a[c],a[c]=d);return a};
cpmzone.prototype.show=function(a){this.size=a.size;this.db=(this.db=a.is_db)?this.db:0;var c=document.domain,c=c.replace("www.",""),d=c.split("."),b="",e="",c=document,h=c.createElement("style");if("undefined"==typeof f)var f="http://admicro2.vcmedia.vn/adt/cpc/";"4k"==a.type&&"160x600"==a.size?(e="#cpmzone{clear:both;width:160px;height:auto;text-align:left;overflow:hidden;margin:0 auto}#cpmzone *{text-decoration:none;font-family:tahoma,arial!important;_font-family:tahoma, arial;font-size:11px;color:#333;text-transform:none!important;_text-transform:none;margin:0;padding:0}#cpmzone .ssvzContent{clear:both;overflow:hidden;background:#fff}#cpmzone .ssvzContent .ssvzMid{background:#FFF;height:auto}#cpmzone .ssvzHeader{background:url("+f+
"ssvborder.png) repeat-x 5px -18px;height:21px;line-height:21px}#cpmzone .ssvHeaderBr{background:url("+f+"ssvtop.png) repeat-y 0 0;clear:both;overflow:hidden}#cpmzone .ssvzLogo{border:0;width:140px;height:21px;line-height:21px;background:url("+f+"ssvtop.png) no-repeat -3px 0;margin:0;padding:0}#cpmzone .ssvzBuy{border:0;width:140px;height:21px;background:url("+f+"ssvtop.png) no-repeat -3px -21px}#cpmzone #cpmzone_items{clear:both;margin:0}#cpmzone_items .adv_items{clear:both;height:216px;overflow:hidden;padding-top:5px;padding-right:7px;margin-left:7px}#cpmzone_items .ssvzBorder{background:#e5e5e5;height:1px}#cpmzone .ssvzclear,#cpmzone_items .adv_items .ssvzimage{clear:both}",
b=b+'<div class="ssvHeaderBr"><div class="ssvHeaderBrRight"><div class="ssvzHeader">'+('<a title="Mua qu\u1ea3ng c\u00e1o"  href="http://admarket.admicro.vn/?utm_source=box_'+d[0]+'&utm_medium=banner&utm_campaign=PR06201" target="_blank"><img vspace="0" hspace="0" class="ssvzBuy" src="http://admicro2.vcmedia.vn/adt/cpc/zoneimages/spacer.gif" border="0" align="right" /></a></div></div></div>'),b+='<div class="ssvzContent"><div class="ssvzRight"><div class="ssvzMid">',b+='<div id="cpmzone_items"></div><div class="ssvzclear"><span></span></div>',
b+="</div></div></div>",b+='<div class="ssvHeaderBrRight"><div class="ssvzHeader"><div class="ssvHeaderBrRight"> ',b+='<a title="Mua qu\u1ea3ng c\u00e1o" href="http://admarket.admicro.vn/?utm_source=box_'+d[0]+'&utm_medium=banner&utm_campaign=PR06201" target="_blank"><img class="ssvzLogo" vspace="0" hspace="0" border="0" align="left" src="http://admicro2.vcmedia.vn/adt/cpc/zoneimages/spacer.gif"></a></div></div></div>'):"4k"==a.type&&"200x167"==a.size?e="#cpmzone{clear:both;width:200px;height:auto;text-align:left;margin:0 auto} #cpmzone img, #cpmzone embed, #cpmzone object{width:200px; height:167px;}":
"4k"!=a.type&&"7k"!=a.type||0!=a.is_db?"7k"==a.type&&"980x90"==a.size?(e="#cpmzone{clear:both;width:980px;height:auto;text-align:left;margin:0 auto}#cpmzone_banner_left{float:left; width:468px;}#cpmzone_banner_right{float:right; width:468px;},#cpmzone_banner{clear:both; width:980px; margin:0 auto;}",b+='<div id="cpmzone_items"></div>'):"7k"==a.type&&"300x600"==a.size&&(e="#cpmzone{clear:both;width:300px;height:auto;text-align:left;margin:0 auto}#cpmzone_banner{clear:both;}",b+='<div id="cpmzone_items"></div>'):
e="#cpmzone{clear:both;text-align:left;margin:0 auto}";b=b.replace(/cpmzone/g,"cpmzone_"+this.zid);h.type="text/css";c.getElementsByTagName("head")[0].appendChild(h);e=e.replace(/cpmzone/g,"cpmzone_"+this.zid);h.styleSheet?h.styleSheet.cssText=e:h.appendChild(c.createTextNode(e));f=c.getElementById("cpmzone_"+this.zid);try{f?(f.innerHTML=b,0<this.banIframe.length&&this.renderIframe()):c.write('<div id="cpmzone_'+this.zid+'">'+b+"</div>")}catch(n){}f=this.getData(a.lst);b="";d=a.df;if(0<f.length)if(f=
this.Shuffle(f),"4k"==a.type)b+=this.renderBanner(a.lst[f[0]]),"160x600"==a.size&&(1<f.length?b=b+'<div style="clear:both; height:10px;"><span></span></div>'+this.renderBanner(a.lst[f[0]]):0<a.df.length&&(b+='<div style="clear:both; height:10px;"><span></span></div>',d=this.Shuffle(d),b+=this.renderBanner(d[0])));else{if("7k"==a.type)if("300x600"==a.size||"980x90"==a.size){for(var l=!1,h=e=0,k=f.length;h<k;h++)184455==a.lst[h].bid&&h!=f[0]&&(e=h,l=!0);if(!0==l)for(l=f[0],h=1,k=f.length;h<k;h++)f[h]==
e&&(f[0]=e,f[h]=l);e=a.lst[f[0]];"300x600"==a.size?(b=""!=e.src_exp?b+this.renderBannerExp(e):b+this.renderBanner(e),600!=e.height&&(1<f.length?(b+='<div style="clear:both; height:10px;"><span></span></div>',e=a.lst[f[1]],b=""!=e.src_exp?b+this.renderBannerExp(e):b+this.renderBanner(e)):0<a.df.length&&(b+='<div style="clear:both; height:10px;"><span></span></div>',d=this.Shuffle(d),e=d[0],b+=this.renderBanner(e)))):980==e.width?b=""!=e.src_exp?b+this.renderBannerExp(e):b+this.renderBanner(e):(b=""!=
e.src_exp?b+('<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBannerExp(e)+"</div>"):b+('<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBanner(e)+"</div>"),1<f.length?(e=a.lst[f[1]],b=""!=e.src_exp?b+('<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBannerExp(e)+"</div>"):b+('<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(e)+"</div>")):0<a.df.length&&(d=this.Shuffle(d),e=d[0],b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(e)+"</div>"))}else e=
a.lst[f[0]],b=""!=e.src_exp?b+this.renderBannerExp(e):b+this.renderBanner(e)}else"4k"==a.type&&"160x600"==a.size?(f=document.getElementById("cpmzone_"+this.zid),f.style.display="none"):"980x90"==a.size||"300x600"==a.size?0<d.length&&(1<d.length?"980x90"==a.size?(b+='<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBanner(d[0])+"</div>",b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(d[1])+"</div>"):(b+=this.renderBanner(a.lst[f[0]]),b+='<div style="clear:both; height:10px;"><span></span></div>',
b+=this.renderBanner(a.lst[f[1]])):"980x90"==a.size?(b+='<div id="cpmzone_'+this.zid+'_banner_left">'+this.renderBanner(d[0])+"</div>",b+='<div id="cpmzone_'+this.zid+'_banner_right">'+this.renderBanner(d[0])+"</div>"):(b+=this.renderBanner(a.lst[f[0]]),b+='<div style="clear:both; height:10px;"><span></span></div>',b+=this.renderBanner(a.lst[f[0]]))):0<d.length?b+=this.renderBanner(d[Math.floor(Math.random()*d.length)]):(f=document.getElementById("cpmzone_"+this.zid),f.style.display="none");("4k"==
a.type&&"160x600"==a.size||"7k"==a.type&&"300x600"==a.size||"7k"==a.type&&"980x90"==a.size?c.getElementById("cpmzone_"+this.zid+"_items"):c.getElementById("cpmzone_"+this.zid)).innerHTML=b;0<this.banIframe.length&&this.renderIframe()};

function adoverlay(){if(!_ovelayShow)return null;this.domain="http://"+document.domain+"/";this.Shuffle=function(b){for(var c,d,e=b.length;e;c=parseInt(Math.random()*e),d=b[--e],b[e]=b[c],b[c]=d);return b};this.logging=function(b,c,d){return c?"http://c.logging.admicro.vn/_adc.html?"+b:d?"http://logging.admicro.vn/_zc.1.gif?"+b:"http://logging.admicro.vn/_adv.gif?"+b};this.FlashText=function(b){return b.replace(/<(span|strong|b)([^>]*)>(.*?)<\/(span|strong|b)>/g,"$3")};if("undefined"!=typeof _ssv_tvc){var h=
_ssv_tvc.z,c=_ssv_tvc.data,g=[],d=[],e=",0,",i=",0,";if("undefined"!=typeof ADS_CHECKER)var e=a=ADS_CHECKER.getCookie("__R"),b=ADS_CHECKER.getCookie("__RC"),e=""==e?",0,":","+e+",",i=""==b?",0,":","+b+",";for(var b=0,j=c.length;b<j;b++){var f=","+c[b].l+",";(-1!=f.indexOf(",1,2,3,")||-1!=f.indexOf(",3,2,1,")||-1!=f.indexOf(",,")||-1!=f.indexOf(e)||-1!=f.indexOf(i))&&d.push(c[b])}c=[];d=this.Shuffle(d);if(3>=d.length)c=d;else for(b=0;3>b;b++)c.push(d[b]);if(c)for(b=0;b<c.length;b++)c[b].title=this.FlashText(c[b].title),
c[b].content=this.FlashText(c[b].content),d={},d.adThumb=c[b].image,d.adTitle=c[b].title,d.adContent=c[b].content,d.adLink=this.logging("adm_domain="+encodeURIComponent(document.URL)+"&adm_campaign="+c[b].cid+"&adm_aditem="+c[b].bid+"&adm_zoneid="+h+"&adm_channelid=-1&adm_rehttp="+encodeURIComponent(c[b].link+(-1!=c[b].descr.indexOf("muachung.vn")?"?ref="+encodeURIComponent(document.URL)+"&bi="+c[b].bid+"&ci="+c[b].cid:"")),!0,!0),d.adDomain=c[b].descr,d.adView=this.logging("adm_aditem="+c[b].bid+
"&adm_campaign="+c[b].cid+"&adm_channelid=-1&adm_domain="+encodeURIComponent(document.URL)+"&adm_zoneid="+h,!1,!1),g.push(d);return 0<g.length?g:null}return null};


var _preloadRun={preroll:{cpc:[],cpm:[]},postroll:{cpc:[],cpm:[]}};


var wPrototype={wdHeight:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerHeight:b.documentElement&&b.documentElement.clientHeight?a=b.documentElement.clientHeight:b.body&&b.body.clientHeight&&(a=b.body.clientHeight);return a},wdWidth:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerWidth:b.documentElement&&b.documentElement.clientWidth?a=b.documentElement.clientWidth:b.body&&b.body.clientWidth&&(a=b.body.clientWidth);return a},getElementTop:function(a){var b=
document;if(b.getElementById)var c=b.getElementById(a);else b.all&&(c=b.all[a]);if(null!=c){yPos=c.offsetTop;for(tempEl=c.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 150},getElementWidth:function(a){return document.getElementById(a).clientWidth},getElementLeft:function(a){var b,c=document;c.getElementById?b=c.getElementById(a):c.all&&(b=c.all[a]);a=b.offsetLeft;for(b=b.offsetParent;null!=b;)a+=b.offsetLeft,b=b.offsetParent;return a},scrollTop:function(){var a=
document,b=a.body.scrollTop;0==b&&(b=window.pageYOffset?window.pageYOffset:a.body.parentElement?a.body.parentElement.scrollTop:0);return b},scrollLeft:function(){var a=document,b=window.pageXOffset?window.pageXOffset:0,c=a.documentElement?a.documentElement.scrollLeft:0,a=a.body?a.body.scrollLeft:0,b=b?b:0;if(c&&(!b||b>c))b=c;return a&&(!b||b>a)?a:b},bdWidth:function(){var a=document;return bodyWidth=Math.max(Math.max(a.body.scrollWidth,a.documentElement.scrollWidth),Math.max(a.body.offsetWidth,a.documentElement.offsetWidth),
Math.max(a.body.clientWidth,a.documentElement.clientWidth))},bdHeight:function(){var a=document;return Math.max(Math.max(a.body.scrollHeight,a.documentElement.scrollHeight),Math.max(a.body.offsetHeight,a.documentElement.offsetHeight),Math.max(a.body.clientHeight,a.documentElement.clientHeight))}};
//bannerdefault

document.write('<script language="javascript" src="http://admicro1.vcmedia.vn/cpc/ssvzone_default.js"></script>');

function _admloadJs(c,a){var b=document.createElement("script");document.getElementsByTagName("head")[0].appendChild(b);b.onload=function(){"function"==typeof a&&a();a=null};b.onreadystatechange=function(){if(4==b.readyState||"complete"==b.readyState)"function"==typeof a&&a(),a=null};b.src=c}

(function () {
    var _admDomain = document.domain+'',
        a = document.createElement("script");
    a.type = "text/javascript";
    a.async = !0;
	if(_admDomain=='linkhay.com' || _admDomain=='wstat.wada.vn' || _admDomain=='soha.vn' ){
    	a.src = "http://admicro1.vcmedia.vn/core/adm_tracking_3rd.js?id=" + Math.random();
	}
	else{
		a.src = "http://admicro1.vcmedia.vn/core/adm_tracking.js?id=" + Math.random();
	}
    var b = document.getElementsByTagName("script")[0];
    b.parentNode.insertBefore(a, b)
})();


var _admSticky=[],_admStickyId=[],_admFSticky=200,_admAppBanner=[],admURL=document.URL,htmladstest="";


if("undefined"==typeof __arCPCBL)var __arCPCBL=[];var arrCPCDf={city:[],area:[],check:!1};Array.prototype.indexOf||(Array.prototype.indexOf=function(l,r){var b=this.length,a=Number(r)||0,a=0>a?Math.ceil(a):Math.floor(a);for(0>a&&(a+=b);a<b;a++)if(a in this&&this[a]===l)return a;return-1});
(function(l){var r=function(){},b=r.prototype;b.trkItem=[];b.arrFav={};b.df=[];b.arrCity=[];b.arrArea=[];b.zoneid=-1;b.template="";b.css="";b.link3rd=[];b.rand_limit=4;b.arrayArea=function(a){for(var d=[],c=[],e=a.length,f=/,[1|2|3],[1|2|3],[1|2|3],/g,g=","+ADS_Location+",",h=","+ADS_City+",",b=0;b<e;b++){var j=","+a[b].l+",",q=","+a[b].la+",";f.test(j)||",,"==j||-1!=j.indexOf(g)||-1!=j.indexOf(h)?d.push(a[b]):-1!=q.indexOf(g)&&c.push(a[b])}return{arrCity:d,arrArea:c}};b.rankMulti=function(a,d){for(var c in a)a[c].r=
parseInt(a[c].r)+d;return a};b.getDataLog=function(a){var d="",c;for(c in a)d+="Bid:"+a[c].bid+", Rank:"+a[c].r+", Location:"+a[c].l+", Location Area:"+a[c].la+"--";return d};b.loghtml="";b.init=function(a){var d=[],c=ADS_CHECKER.getQuery("i"),e=[],f=!1,g=/,[1|2|3],[1|2|3],[1|2|3],/g,b=","+ADS_Location+",",k=","+ADS_City+",",j=!1,q=[],j=!("1"==ADS_City||"2"==ADS_City||"3"==ADS_City||"4"==ADS_City||"5"==ADS_City||"0"==ADS_City||70<parseInt(ADS_City)),c=""==c&&isNaN(c)?0:parseInt(c),m;for(m in a){var n=
this.toArray(a[m]),p;for(p in n)if(n[p].bid==c&&!1==f&&(f=!0,this.trkItem.push(n[p])),j&&"103"!=m&&"203"!=m&&"201"!=m&&"202"!=m&&"202"!=m&&"231"!=m&&"232"!=m&&"233"!=m&&"234"!=m&&"235"!=m){var l=","+n[p].l+",";(g.test(l)||",,"==l||-1!=l.indexOf(b)||-1!=l.indexOf(k))&&!ADS_CHECKER.in_array(n[p].bid,__arCPCBL)&&!ADS_CHECKER.in_array(n[p].bid,q)?(q.push(n[p].bid),d.push(n[p])):!ADS_CHECKER.in_array(n[p].bid,__arCPCBL)&&!ADS_CHECKER.in_array(n[p].bid,q)&&(e.push(n[p]),q.push(n[p].bid))}}j&&(this.arrCity=
d,this.arrArea=e)};b.sortRank=function(a){for(var d={},c=a.length,e=0;e<c-1;e++)for(var f=e+1;f<c;f++)parseInt(a[e].r)<parseInt(a[f].r)&&(d=a[e],a[e]=a[f],a[f]=d);return a};b.array_merge=function(a,d){for(var c=[],e=[],f=0,g=arguments.length;f<g;f++)for(var b in arguments[f])if(-1==c.indexOf(arguments[f][b].bid))c.push(arguments[f][b].bid),e.push(arguments[f][b]);else{var k=c.indexOf(arguments[f][b].bid);e[k].r=parseInt(e[k].r)+parseInt(arguments[f][b].r)}return e};b.Shuffle=function(a){for(var d,
c,e=a.length;e;d=parseInt(Math.random()*e),c=a[--e],a[e]=a[d],a[d]=c);return a};b.toArray=function(a){var d=[];for(x in a)d.push(a[x]);return d};b.escapeHtml=function(a){a=a.replace(/<(span|strong|b)[^>]*>(.*?)<\/(span|strong|b)>/g,"$2");return a=a.replace(/\"/g,"&quot;")};b.dataFav=function(a){var d=[],c={201:{keyname:"ADS_Gender",value:1},202:{keyname:"ADS_Gender",value:2},203:{keyname:"ADS_Game",value:1},231:{keyname:"ADS_Age",value:1},232:{keyname:"ADS_Age",value:2},233:{keyname:"ADS_Age",value:3},
234:{keyname:"ADS_Age",value:4},235:{keyname:"ADS_Age",value:5}},e;for(e in c)"undefined"!=typeof a[e]&&(l[c[e].keyname]==c[e].value&&(d=this.array_merge(d,a[e])),delete a[e]);c={};e=0;for(var f=d.length;e<f;e++)c[d[e].bid]=d[e];this.arrFav=c;return a};b.getCookie=function(a){return ADS_CHECKER.getStorage(a)};b.setCookie=function(a,d){ADS_CHECKER.setStorage(a,d,0,"/");return!0};b.removeZoneCook=function(a){for(var d=this.getCookie("cpcSelfServ"),c=a.length-1,e=0;e<c;e++)d=d.replace(a[e]+",","");this.setCookie("cpcSelfServ",
d,1,1)};b.addCookie=function(a){var d=this.getCookie("cpcSelfServ");this.setCookie("cpcSelfServ",d+a,1,1)};b.choseBlock=function(a){var d=ADS_CHECKER.getStorage("cpcSelfServ"),c=0,e=Math.floor((new Date).getTime()/1E3);if(-1!=d.indexOf(this.zoneid+"_b_"))var f=d.indexOf(this.zoneid+"_b_"),c=d.indexOf(",",f),f=d.substring(f,c),c=this.explode("_",f),b="",b=4==c.length?parseInt(c[3]):0,c=4==c.length?parseInt(c[2]):0,c=900<=e-b?Math.floor(Math.random()*a):c,b=900<=e-b?this.zoneid+"_b_"+c+"_"+e:this.zoneid+
"_b_"+c+"_"+b,d=d.replace(f,b);else c=Math.floor(Math.random()*a),d+=this.zoneid+"_b_"+c+"_"+e+",";ADS_CHECKER.setStorage("cpcSelfServ",d,0,"/");return c};b.addDefault=function(a,d,c){var e=!1,f="";if(0<d.length&&0<c){3<arguments.length&&(e="string"==typeof arguments[3]?!0:e);var b=Math.min(d.length,c),h=[],k=0;if(e){for(var f=arguments[3],e=0,j=a.length;e<j;e++)h.push(a[e][f]);e=0;for(j=d.length;e<j&&(ADS_CHECKER.in_array(d[e][f],h)||!(k++,a.push(d[e]),k==b));e++);}else if(d.length<c)a=d;else{d=
3<arguments.length?d:this.Shuffle(d);for(e=0;e<b;e++)a.push(d[e])}}return a};b.dupItem=function(a,d){var c=a.length,e=0,f=0,b;b=this.Shuffle(a);len2=b.length;if(0<c&&0<d){e=Math.floor(d/c);f=d%c;if(0<e){for(c=0;c<e;c++)for(var h=0;h<len2;h++)a.push(b[h]);0!=f&&(a=this.dupItem(a,f))}if(0<f&&0==e)for(c=0;c<f;c++)a.push(a[c])}return a};b.dataAage=function(a){var d={},c=0,e=ADS_Age,b=!1,g=ADS_CHECKER.getQuery("i"),g=""==g&&isNaN(g)?0:parseInt(g),h;for(h in a)for(var k in a[h])if(a[h][k].bid==g&&!1==b&&
(b=!0,this.trkItem.push(a[h][k])),RegExp(","+e+",","g").test(","+a[h][k].ag+",")||""==a[h][k].ag)"undefined"==typeof d[h]&&(d[h]={}),d[h][k]=a[h][k],c++;return 0==c?[]:d};b.OnLoaded=function(a){var d=!1,d="1"==ADS_City||"2"==ADS_City||"3"==ADS_City||"4"==ADS_City||"5"==ADS_City||"0"==ADS_City||70<parseInt(ADS_City);this.init(a.DATA);a.DATA=this.dataFav(a.DATA);var c=this.arrFav;"undefined"!=typeof a.DATA["103"]&&(this.df=this.toArray(a.DATA["103"]),delete a.DATA["103"]);this.zoneid=a.ZONEID;this.resetDefault();
var e=this.toArray(a.DATA);a=[];var b=this.rand_limit;if(0<e.length)if(d){var d=this.choseBlock(e.length),d=e[d],g;for(g in d)"undefined"!=typeof c[d[g].bid]&&(d[g].r=parseInt(d[g].r)+parseInt(c[d[g].bid].r));c=this.arrayArea(this.toArray(d));d=c.arrCity.length;c.arrCity=this.sortRank(c.arrCity);c.arrArea=this.sortRank(c.arrArea);a=this.addDefault(a,c.arrCity,b-a.length);d=b-a.length;0<d&&(a=this.addDefault(a,c.arrArea,d))}else{var e=this.arrCity,h=this.arrArea;g=0;for(d=e.length;g<d;g++)"undefined"!=
typeof c[e[g].bid]&&(e[g].r=parseInt(e[g].r)+parseInt(c[e[g].bid].r));g=0;for(d=h.length;g<d;g++)"undefined"!=typeof c[h[g].bid]&&(e[g].r=parseInt(e[g].r)+parseInt(c[e[g].bid].r));a=this.addDefault(a,e,b-a.length);d=b-a.length;0<d&&(a=this.addDefault(a,h,d))}a=this.addDefault(a,this.df,b-a.length);a=this.addDefault(a,arrCPCDf.city,b-a.length);a=this.addDefault(a,arrCPCDf.area,b-a.length);0<a.length&&b>a.length&&(a=this.dupItem(a,b-a.length));a.length>b&&(a=this.getItem(a));0<this.trkItem.length&&
(a[0]=this.trkItem[0]);return a=this.Shuffle(a)};b.getItem=function(a){var d=this.getCookie("cpcSelfServ");this.explode(",",d);var d=d.match(RegExp(this.zoneid+"_([0-9]+)","g")),c=[],e=[],c=a;a=this.rand_limit;if(c.length>a)var c=this.choseData(c,a),b=0;else{if(0<e.length)for(var g=this.choseData(e,a-c.length),b=0,h=g.length;b<h;b++)c.push(g[b]);d&&this.removeZoneCook(d);b=0}for(;b<a;b++);16<=e.length&&this.removeZoneCook(d);return c};b.choseData=function(a,d){for(var c=[],b=[],f=0,g=a.length;f<g;f++)for(var h=
0;h<parseInt(a[f].r);h++)c[c.length]=a[f].bid;c=this.Shuffle(c);for(f=0;f<d;f++){g=Math.floor(Math.random()*c.length);for(h=0;h<a.length;h++)if(a[h].bid==c[g]){b.push(a[h]);break}c=ADS_CHECKER.array_diff(c,[c[g]])}return b};b.explode=function(a,d,c){var b={"0":""};if(2>arguments.length||"undefined"==typeof arguments[0]||"undefined"==typeof arguments[1])return null;if(""===a||!1===a||null===a)return!1;if("function"==typeof a||"object"==typeof a||"function"==typeof d||"object"==typeof d)return b;!0===
a&&(a="1");if(c){var f=d.split(a),b=f.splice(0,c-1),f=f.join(a);("undefined"!=typeof f||""!=f||0<f)&&b.push(f);return b}return d.split(a)};b.test=function(){setTimeout("ssvzone_"+this.zoneid+".test()",1E3)};b.resetDefault=function(){if(arrCPCDf.check)return!1;var a=[],b=[],c=/,[1|2|3],[1|2|3],[1|2|3],/g,e=","+ADS_Location+",",f=","+ADS_City+",",g=[];if(void 0!=typeof _ssv_default&&"undefined"!=typeof _ssv_default)for(var g=_ssv_default,h=0,k=g.length;h<k;h++){var j=","+g[h].l+",",l=","+g[h].la+",";
(c.test(j)||",,"==j||-1!=j.indexOf(e)||-1!=j.indexOf(f)||-1!=l.indexOf(f))&&!ADS_CHECKER.in_array(g[h].bid,__arCPCBL)?a.push(g[h]):-1!=l.indexOf(e)&&!ADS_CHECKER.in_array(g[h].bid,__arCPCBL)&&b.push(g[h])}arrCPCDf.city=a;arrCPCDf.area=b;arrCPCDf.check=!0};b.resetVar=function(){b.trkItem=null;b.arrFav=null;b.df=null;b.arrCity=null;b.arrArea=null;b.zoneid=null;b.template=null;b.css=null;b.link3rd=null;b.rand_limit=null};l.admCpcZone=r})(window);


function admExecJs(j,d){var f=j,g=[],e=[];this.trim=function(a){a=a.replace(/^\s+/,"");for(var b=a.length-1;0<=b;b--)if(/\S/.test(a.charAt(b))){a=a.substring(0,b+1);break}return a};this.explode=function(){var a=j.match(/<(script)[^>]*>(.*?)<\/(script)>/gi);if(a)for(var b="",c=0,d=a.length;c<d;c++)f=f.replace(a[c],""),b=a[c].replace(/<(script)[^>]*>(.*?)<\/(script)>/gi,"$2"),""!=this.trim(b)&&g.push(this.trim(b)),(b=a[c].match(/src="([^\"]*)\"/gi))&&e.push(b[0].replace(/src="([^\"]*)\"/gi,"$1"))};
this.getFileScript=function(a){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)};this.explode();if(0<e.length){d=document.getElementById(d);d.innerHTML=f;for(var c=0,h=g.length;c<h;c++)eval(g[c]);c=0;for(h=e.length;c<h;c++)this.getFileScript(e[c])}};

function advfa(b){if("object"==typeof b){var a="";"undefined"!=typeof b.s&&(a=b.s,a=a.toString(),ADS_CHECKER.setStorage("s",a,"","/"));"undefined"!=typeof b.g&&(a=b.g,a=a.toString(),ADS_CHECKER.setStorage("g",a,"","/"));"undefined"!=typeof b.a&&(a=b.a,a=a.toString(),ADS_CHECKER.setStorage("a",a,"","/"))}};
//TVC Popup
function getFlashMovie(a){return-1!=navigator.appName.indexOf("Microsoft")?document.getElementById(a):document[a]}
function admTvcMini(){if("undefined"==typeof admTvcPopup||admTvcPopup)return!1;_admTvcCheckCall=admTvcPopup=!0;var a=getFlashMovie("admID");"undefined"!=typeof a&&("undefined"!=typeof a[1]&&"undefined"!=typeof getFlashMovie("admID")[1].admcallMini&&getFlashMovie("admID")[1].admcallMini(),"undefined"!=typeof a[0]&&"undefined"!=typeof getFlashMovie("admID")[0].admcallMini&&getFlashMovie("admID")[0].admcallMini(),"undefined"!=typeof getFlashMovie("admID").admcallMini&&getFlashMovie("admID").admcallMini(),
setTimeout("hideAddon()",500))}
function admTvcMedium(){if("undefined"==typeof admTvcPopup||!admTvcPopup)return!1;_admTvcCheckCall=admTvcPopup=!1;var a=getFlashMovie("admID");"undefined"!=typeof a&&(showAddon(),"undefined"!=typeof a[1]&&"undefined"!=typeof a[1].admcallMedium&&getFlashMovie("admID")[1].admcallMedium(),"undefined"!=typeof a[0]&&"undefined"!=typeof a[0].admcallMedium&&getFlashMovie("admID")[0].admcallMedium(),"undefined"!=typeof a.admcallMedium&&getFlashMovie("admID").admcallMedium())};

//load banenr default CP
function AdmLoadDefault(g){"1"==ADS_CHECKER.getQuery("admdebug")&&console.log(g);var a=document.getElementById(g),b=a.parentNode.parentNode.id,k=b.match(/([\d]+)/gi),c=k?parseInt(k[0]):0,e=k?parseInt(k[1]):0,k="";if("undefined"!=typeof(0!=c&&0!=e&&_admDefault[c].rotate)){var k="ads_zone"+c+"_slot",f=_admDefault[c].rotate,l=_admDefault[c].effect;g=a.parentNode.id;var p=parseInt(a.parentNode.id.replace("ads_zone"+c+"_banner","")),m=a.parentNode.getAttribute("class"),n="ads_zone"+c,m=parseInt(m.replace("banner",
"")),p=isNaN(p)?0:p;g=a.parentNode.id;a={fillter:function(a){var c=[];if(a)for(var b=0,d=a.length;b<d;b++)a[b].bid!=p&&c.push(a[b]);return c},chose:function(a){for(var c=[],b=0,d=a.length;b<d;b++)a[b].bid!=p&&c.push(a[b]);return c},draw:function(a,b){var d=3<=arguments.length?arguments[2]:0,e=new banner(a[Math.floor(Math.random()*a.length)]),d=e.renderBanner("ads_zone"+c+"_banner"+e.bid,c,Math.random(),"","banner"+d);admExecJs(d,b)}};if(2!=l[e]){_admDefault[c].cpm[e-1]=a.fillter(_admDefault[c].cpm[e-
1]);_admDefault[c].retar[e-1]=a.fillter(_admDefault[c].retar[e-1]);var l=_admDefault[c].cpm[e-1],f=[],j=_admDefault[c].retar[e-1],d=[],f=a.chose(l,p),d=a.chose(j,p);if(0<f.length)a.draw(f,b);else if(0<d.length)a.draw(d,b);else{f=_admDefault[c].rotate;l=_admDefault[c].effect;b={df:[],cpm:[],retar:[]};j=0;for(m=f.length;j<m;j++)if(ADS_CHECKER.in_array(e,f[j]))for(var d=ADS_CHECKER.array_diff(f[j],[e]),h=0,r=d.length;h<r;h++)if(2!=l[d[h]])0<_admDefault[c].cpm[d[h]-1].length&&!ADS_CHECKER.in_array(d[h]-
1,b.cpm)&&b.cpm.push(d[h]-1),0<_admDefault[c].retar[d[h]-1].length&&!ADS_CHECKER.in_array(d[h]-1,b.retar)&&b.retar.push(d[h]-1),0<_admDefault[c][d[h]-1].length&&!ADS_CHECKER.in_array(d[h]-1,b.df)&&b.df.push(d[h]-1);else for(var q=0;q<m;q++)0<_admDefault[c].cpm[d[h]-1][q].length&&!ADS_CHECKER.in_array(d[h]-1,b.cpm)&&b.cpm.push(d[h]-1),0<_admDefault[c].retar[d[h]-1][q].length&&!ADS_CHECKER.in_array(d[h]-1,b.retar)&&b.retar.push(d[h]-1),0<_admDefault[c][d[h]-1][q].length&&!ADS_CHECKER.in_array(d[h]-
1,b.df)&&b.df.push(d[h]-1);0==b.cpm.length&&0<b.retar.length?b.cpm=b.retar:0==b.cpm.length&&(0==b.retar.length&&0<b.df.length)&&(b.cpm=b.df);if(0==b.cpm.length)f=_admDefault[c][e-1],0<f.length&&a.draw(f,g);else if(0<b.cpm.length)if(d=Math.floor(Math.random()*b.cpm.length),k+=b.cpm[d]+1,2!=l[parseInt(b.cpm[d])+1]){if(0<_admDefault[c].cpm[b.cpm[d]].length?a.draw(_admDefault[c].cpm[b.cpm[d]],k):0<_admDefault[c][b.cpm[d]].length&&a.draw(_admDefault[c][b.cpm[d]],k),n=document.getElementById(k))n.style.display=
""}else{e="";j=0;for(m=_admDefault[c].cpm[b.cpm[d]].length;j<m;j++)g=_admDefault[c].cpm[b.cpm[d]][j],a=_admDefault[c][b.cpm[d]][j],0<g.length?(g=new banner(g[Math.floor(Math.random()*g.length)]),e+=g.renderBanner("ads_zone"+c+"_banner"+g.bid,c,Math.random(),"","banner"+(j+1))):0<a.length?(g=new banner(a[Math.floor(Math.random()*a.length)]),e+=g.renderBanner("ads_zone"+c+"_banner"+g.bid,c,Math.random(),"","banner"+(j+1))):0!=window[n].style.banner_default[b.cpm[d]+1]&&(a=window[n].style.banner_default[b.cpm[d]+
1],a=new banner({bannertype:0,bid:0,title:"",type:a.type,link:a.link,src:a.src,width:a.width,height:a.height,created:null,expired:null,slotIdx:d+1,attr:null,terms:a.terms,clicks:0,views:0,cpname:"",counter:!1,iframe:0,fix_ie:0,sort:0,link_clicks:null,link_views:null}),a.process(),a.bool&&(e+=a.renderBanner("ads_zone"+c+"_banner_slot"+(d+1)+"_"+(j+1),this.zoneid,Math.random(),"","banner"+(j+1))));if(n=document.getElementById(k))n.style.display="",admExecJs(e,k)}}}else if(_admDefault[c].cpm[e-1][m-
1]=a.fillter(_admDefault[c].cpm[e-1][m-1]),l=_admDefault[c].cpm[e-1][m-1],f=[],f=a.chose(l,p),0<f.length)a.draw(f,g,m);else if(l=_admDefault[c][e-1][m-1],f=a.chose(l,p),0<f.length)a.draw(f,g,m);else if(0!=window[n].style.banner_default[e]&&(a=window[n].style.banner_default[e],e="",a=new banner({bannertype:0,bid:0,title:"",type:a.type,link:a.link,src:a.src,width:a.width,height:a.height,created:null,expired:null,slotIdx:d+1,attr:null,terms:a.terms,clicks:0,views:0,cpname:"",counter:!1,iframe:0,fix_ie:0,
sort:0,link_clicks:null,link_views:null}),a.process(),a.bool&&(e+=a.renderBanner("ads_zone"+c+"_banner_slot"+(d+1)+"_"+(j+1),this.zoneid,Math.random(),"","banner"+m)),n=document.getElementById(g)))n.style.display="",admExecJs(e,g)}}
function admExecJs(g,a){"1"==ADS_CHECKER.getQuery("admdebug")&&console.log("id:"+a);var b=g,k=[],c=[];this.trim=function(a){a=a.replace(/^\s+/,"");for(var b=a.length-1;0<=b;b--)if(/\S/.test(a.charAt(b))){a=a.substring(0,b+1);break}return a};this.explode=function(){var a=g.match(/<(script)[^>]*>(.*?)<\/(script)>/gi);if(a)for(var e="",f=0,j=a.length;f<j;f++)b=b.replace(a[f],""),e=a[f].replace(/<(script)[^>]*>(.*?)<\/(script)>/gi,"$2"),""!=this.trim(e)&&k.push(this.trim(e)),(e=a[f].match(/src="([^\"]*)\"/gi))&&
c.push(e[0].replace(/src="([^\"]*)\"/gi,"$1"))};this.getFileScript=function(a){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)};this.explode();var e=document.getElementById(a);e&&(e.innerHTML=b,window.setTimeout(function(){e.style.display=""},1E3));if(0<c.length){for(var f=0,l=k.length;f<l;f++)eval(k[f]);f=0;for(l=c.length;f<l;f++)this.getFileScript(c[f])}};

//reset ip nuoc ngoai
/*
if(ADS_Location ==0 ||  ADS_City==101){
	_admloadJs("http://logging.admicro.vn/_tkip.js");
}
*/
(function(){
	if('localStorage' in window && window['localStorage'] !== null){
		var ver=ADS_CHECKER.getStorage("ver");
		if(ver=='' || ver.replace(/timestamp_([0-9]+)\,/g,'')!='19'){
			localStorage.clear();
			ADS_CHECKER.setStorage('ver', '19', '', '/');
		}
	}
	var _urlDomain=document.domain+'';
	if(_urlDomain.indexOf('tamdiem.net')!=-1 || _urlDomain.indexOf('hay88.com')!=-1){
		_admloadJs("http://logging.admicro.vn/isporn?md5="+_admMd5(document.URL+'')+'&uri='+encodeURIComponent(document.URL));
	}
	
	_admloadJs("http://logging.admicro.vn/_cpm4k.js");
	_admloadJs('http://logging.admicro.vn/ps');
	_admloadJs('http://logging.admicro.vn/cpcbl');

	_admloadJs("http://logging.vietid.net/tracking_active_user.php");
		
	/*
	if(_urlDomain.indexOf('genk.vn')!=-1 || _urlDomain.indexOf('gamek.vn')!=-1){
			_admloadJs("http://testlogging.vietid.net/tracking_active_user.php");
	}
	else{
			_admloadJs("http://logging.vietid.net/tracking_active_user.php");
	}*/
	
	
})();
