package com.k53ca.lotterylive.data;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

	private final DaoConfig ketQuaXoSoDaoConfig;

	private final KetQuaXoSoDao ketQuaXoSoDao;

	public DaoSession(SQLiteDatabase db, IdentityScopeType type,
			Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
		super(db);

		ketQuaXoSoDaoConfig = daoConfigMap.get(KetQuaXoSoDao.class).clone();
		ketQuaXoSoDaoConfig.initIdentityScope(type);

		ketQuaXoSoDao = new KetQuaXoSoDao(ketQuaXoSoDaoConfig, this);

		registerDao(KetQuaXoSo.class, ketQuaXoSoDao);
	}

	public void clear() {
		ketQuaXoSoDaoConfig.getIdentityScope().clear();
	}

	public KetQuaXoSoDao getKetQuaXoSoDao() {
		return ketQuaXoSoDao;
	}

}
